### ISSUE TITLE
Add typescript typings

### ISSUE THREAD

**Issue by Xyfi** [vkbansal/react-contextmenu#10]
Would it be possible to write typescript typings and add them to DefinitelyTyped? I'm not yet confident enough with typescript to do it myself.

**Comment by vkbansal** [comment]
@Xyfi I too am not familiar with typescript and its ecosystem.

It would be great if anyone could help me with it.

**Comment by akosyakov** [comment]
@Xyfi Do you have already d.ts file to share?

**Comment by Xyfi** [comment]
Wow, that's a long time ago :). I'm sorry, but I moved on to another project since then, and am no longer using react-contextmenu.

**Comment by arangde** [comment]
@vkbansal, I made typedef .d.ts file in my typescript project.
Please review https://github.com/arangde/typescript-react-contextmenu/blob/master/react-contextmenu.d.ts

**Comment by vkbansal** [comment]
Looks good enough to start with. Can you open a PR with it?

**Comment by vkbansal** [comment]
@arangde Can you open a PR?
