### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by yotamberk** [vkbansal/react-contextmenu#100]
## Version
1.2.0

There is support rtl for submenus which is great.
## Expected Behavior
I would expect that defining `rtl` to be `true` will open the contextmenu to the left of the mouse.

## Actual Behavior
the contextmenu opens to the right of the mouse position.

**Comment by vkbansal** [comment]
v1.2.0 is no longer supported. But this is nice to have feature.

Can you open a PR with the feature by any chance?

**Comment by yotamberk** [comment]
I've tried, but for some reason the eslint goes crazy and won;t let me build. (I'm using windows, and it seems there is a LF to CRLF problem)

**Comment by vkbansal** [comment]
You can set line endings in your editor. What editor are you using?

**Comment by yotamberk** [comment]
Sublime

**Comment by vkbansal** [comment]
https://github.com/sindresorhus/editorconfig-sublime this plugin should help you

**Comment by yotamberk** [comment]
Awesome. Expect a PR the next few days

**Comment by vkbansal** [comment]
Great!!

**Comment by yotamberk** [comment]
When doing `npm install` I get in my cmd ` error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style`. How can I solve this?

**Comment by vkbansal** [comment]
https://help.github.com/articles/dealing-with-line-endings/
this should help you

**Comment by yotamberk** [comment]
still getting a problem: `Cannot find module 'eslint-config-vkbansal/react'`

**Comment by vkbansal** [comment]
`npm install eslint-config-vkbansal`

**Comment by vkbansal** [comment]
Any Update on this?

**Comment by yotamberk** [comment]
I've never managed to get the build to work...

**Comment by vkbansal** [comment]
Are you using windows machine?

**Comment by yotamberk** [comment]
yes

**Comment by vkbansal** [comment]
I'll try setting up this on a windows machine today then.

**Comment by vkbansal** [comment]
I tried setting up on Windows Machine and it worked.

![image](https://user-images.githubusercontent.com/5930351/26861224-1de50e82-4b60-11e7-9e94-609700bed1e8.png)

**Comment by yotamberk** [comment]
I'm still having problems with this. I really would like to fix this when I have more time
