### ISSUE TITLE
How generate menus based on the items that was clicked ?

### ISSUE THREAD

**Issue by hilde2** [vkbansal/react-contextmenu#104]
Hi ! Can this lib handle this ? I can't find how make it work

Example :
http://jchristman.github.io/react-context-menus/examples-dynamic-menus.html

**Comment by vkbansal** [comment]
https://vkbansal.github.io/react-contextmenu/#/multiple-menus

doesn't ^ solve your problem?

**Comment by hilde2** [comment]
Well https://vkbansal.github.io/react-contextmenu/#/dynamic-menu was what I was looking for, thanks !
