### ISSUE TITLE
Bug with multiple click bindings

### ISSUE THREAD

**Issue by valentinvichnal** [vkbansal/react-contextmenu#109]
I have opened #82 

I found out what was causing my original issue wasn't multiple targets.
It was because I was using [https://github.com/RubaXa/Sortable](https://github.com/RubaXa/Sortable)
I tried to create a context on sortable items, when I right clicked, it started the sorting process and blocked the context trigger click.

Any workarounds for this?

**Comment by phamvankhang** [comment]
i got the same problem

**Comment by valentinvichnal** [comment]
I tried with mutliple id after that, was it a Sortable item where it worked?

**Comment by Emeroj** [comment]
@valentinvichnal I'm having the same exact issue with https://github.com/RubaXa/Sortable.

Did you find a solution to this?

**Comment by valentinvichnal** [comment]
@Emeroj Unfortunately not, I stopped using the two together.
