### ISSUE TITLE
Missing something obvious with renderTag

### ISSUE THREAD

**Issue by ewal** [vkbansal/react-contextmenu#11]
I'm trying to override the renderTag prop with a table cell element.
This is how I do it but with no luck. What am I doing wrong?

export default ContextMenuLayer("identifier", (props) => {
		renderTag: 'td'
})(MyComponent);

**Comment by vkbansal** [comment]
You must do the following.
```
const Layer = ContextMenuLayer("identifier")(MyComponent);

<Layer renderTag="td" />
```

**Comment by ewal** [comment]
I'm trying to implement the context menu in a table where each table row (not td as I wrote in the initial post) has some actions on them but I can't find a easy solution to my problem. Whichever approach I use I end up with invalid html output. 
I previously used the `0.2.1` version in another project and it worked well with table rows, no extra div wrapper rendered to the DOM.
What would be your approach to my problem with the current version?

**Comment by vkbansal** [comment]
I've updated readme and also added example usage (with demo).
