### ISSUE TITLE
ContextMenu onContextMenu should prevent default

### ISSUE THREAD

**Issue by codeart1st** [vkbansal/react-contextmenu#112]
In `ContextMenu`class `render`method is an `onContextMenu` prop, which bind the `handleHide` method to the `nav`element.
`handleHide` hasn't a `preventDefault`, so when someone tries to open an contextmenu with right click on the contextmenu itself, the browser system contextmenu will show up instead.
I would recommend a simple `onContextMenu={e => e.preventDefault()}`. With this change the browser system contextmenu won't show up and the react-contextmenu will hide regardless correctly.

**Comment by vkbansal** [comment]
My intention behind it was for easier debugging while development, But I agree with your point.

We can add something like:
```js
if (process.env.NODE_ENV === 'production') {
  e.preventDefault();
}
```

**Comment by codeart1st** [comment]
This would be nice.
