### ISSUE TITLE
Text Content Removed from Children (2.6.1)

### ISSUE THREAD

**Issue by skipjack** [vkbansal/react-contextmenu#118]
## Version
2.6.1

## Test Case
Here is [an example](https://www.webpackbin.com/bins/-KldcQNzGzkJ5GEyZ_rO). If you right click you'll see the menu pop up but empty. If you inspect the DOM, you'll notice that the child elements are rendered but with no text content.

## Steps to reproduce
Render normal children (not using `<MenuItem>`) within a `<ContextMenu>`.

## Expected Behavior
Children should remain intact.

## Actual Behavior
Child elements are being modified and somehow their text content is being removed. I tried `2.6.0` and `2.5.2` which both work fine so this must have been introduced in the latest version.

**Comment by vkbansal** [comment]
@codeart1st I think your last change 1a21fba69c9dab71b63292abebc23113e55b464c is causing this.

**Comment by codeart1st** [comment]
No problem I will look into this.

**Comment by codeart1st** [comment]
https://github.com/vkbansal/react-contextmenu/blob/master/src/AbstractMenu.js#L105 raw strings are no object types of `ReactElementSymbol` and it wasn't a good idea to skip those childs and nullify them.

**Comment by skipjack** [comment]
@codeart1st no problem, thanks for jumping on this so quickly! Please ping me when a patch is released.

**Comment by vkbansal** [comment]
Published v2.6.2

**Comment by skipjack** [comment]
Awesome -- updated, tested and confirmed.
