### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

### ISSUE THREAD

**Issue by stevenmusumeche** [vkbansal/react-contextmenu#121]
## Version
2.2.1

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

## Steps to reproduce
Unsure but it happens in production (rarely)

## Expected Behavior
No uncaught errors

## Actual Behavior
Line 76: Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

	
            innerWidth = _window.innerWidth,
            innerHeight = _window.innerHeight;
            var rect = _this.menu.getBoundingClientRect(); // <-- error on this line
            var menuStyles = {
                top: y,
                left: x

**Comment by vkbansal** [comment]
It would be helpful if I can get steps to reproduce.

**Comment by stevenmusumeche** [comment]
Yea, totally understand, I can't reproduce it either but our error tracking is finding it in the wild.  I noticed a similar error which happens in the same file because _this.menu is null.

**Comment by vkbansal** [comment]
OK. I'll take a stab at it over the weekend.

**Comment by skipjack** [comment]
I'm seeing this as well:

![image](https://user-images.githubusercontent.com/8988697/27188799-5895f75e-51bd-11e7-9f64-8b8af1f605c8.png)

Which stems from [line 147](https://github.com/vkbansal/react-contextmenu/blob/master/src/ContextMenu.js#L147) in `ContextMenu.js`. It's [line 58](https://github.com/vkbansal/react-contextmenu/blob/master/src/ContextMenu.js#L58) that triggers this though -- I think the `window.requestAnimationFrame || setTimeout` is causing it to be called after the component has unmounted in certain scenarios.

It's inconsistent for me as well though I am able to reproduce it consistently when changing urls via react-router. I don't have time to throw together an example at the moment but I'm pretty sure what I described above is the cause.

**Comment by skipjack** [comment]
Also seeing:

![image](https://user-images.githubusercontent.com/8988697/27189446-5e9d54b0-51bf-11e7-93d8-a0f17229b23b.png)

Which seems to be caused by trying to read styles after the component has unmounted.

**Comment by vkbansal** [comment]
Which browser are you guys seeing this on?

**Comment by skipjack** [comment]
Chrome for me.

**Comment by stevenmusumeche** [comment]
Latest Chrome for me as well.

**Comment by vkbansal** [comment]
Released a patch for this. Please open issues if you find such errors in future.

**Comment by skipjack** [comment]
Tested and confirmed the fix, thanks @vkbansal!

**Comment by stevenmusumeche** [comment]
same here, thanks so much @vkbansal you rock
