### ISSUE TITLE
Missing dependency on install

### ISSUE THREAD

**Issue by kevinch** [vkbansal/react-contextmenu#122]
## Version
2.6.2

## Steps to reproduce
`git clone` & `npm start`

## Expected Behavior
Starting local server with app.

## Actual Behavior
Error: `sh: http-server: command not found`

## Fix
`npm i http-server --save-dev`

**Comment by vkbansal** [comment]
Would you like to open a PR with fix?

**Comment by vkbansal** [comment]
Fixed it.
