### ISSUE TITLE
Broken css-link in usage.md

### ISSUE THREAD

**Issue by faiwer** [vkbansal/react-contextmenu#124]
I read it in documentation page ([usage.md](https://github.com/vkbansal/react-contextmenu/blob/master/docs/usage.md))

> Note: This package does note include any styling by default. You can use [react-contextmenu.css](https://github.com/vkbansal/react-contextmenu/blob/master/docs/examples/react-contextmenu.css) from examples for quick setup.

But link is broken. I'm thinking right url is `https://github.com/vkbansal/react-contextmenu/blob/master/examples/react-contextmenu.css`.

**Comment by vkbansal** [comment]
Would you like to open PR?
