### ISSUE TITLE
A method for an prevent showing a contextmenu

### ISSUE THREAD

**Issue by faiwer** [vkbansal/react-contextmenu#125]
Hello. There's one small feature request here.  I wanted to show the contextMenu only when user clicks to some dom-tags, and do not show if user clicks on their children-tags, cause users would use some options of native browser menu there. 

I saw source code of `ContextMenuTrigger`, I've found a lot of `callIfExists(this.props.attributes.%method%, event)` calls, but I can't override or prevent showing contextmenu by it. 

Currently I'm stopped at next workaround:

```js
class PatchedContextMenuTrigger extends ContextMenuTrigger
{
	constructor(...args)
	{
		super(...args);
		this.handleContextMenu = wrap(this.handleContextMenu, this.onContextMenu);
	}

	onContextMenu(func, evt, ...args)
	{
		if(evt.target.matches('td'))
			func.call(this, evt, ...args);
	}
}
```

I'm thinking that `<ContextMenuTrigger/>` needs one more property. Something like `shouldMenuShow`  (bool):

```js
<ContextMenuTrigger shouldMenuShow={this.shouldMenuShow}/>
// ...
shouldMenuShow = evt => evt.target.matches(blabla) // or different logic
```

**Comment by vkbansal** [comment]
There is a `disable` prop available on `<ContextMenuTrigger />` isn't it useful?

**Comment by faiwer** [comment]
But how do disable it with `disable` react-prop? Did you mean something like this:

- use react-state on component-owner with property `isContextMenuDisabled`
- turn on it on `attributes.onMouseDown` by condition via `setState`
- turn out it on `attributes.onMouseUp` via `setState`
- use it in `render`-method in `ContextMenuTrigger`-attributes (`disable`, `onMouseDown`, `onMouseUp`)?

Yes, I can. But I think it's too overcomplicated for so simple task. My problem is already solved by `extend`-class solution. But I think functional-way (provide method-checker) would be better solution and more like react-way.

But I'm not insisting on this way. It's only my proposal :)

**Comment by jake-daniels** [comment]
Actually, I expected this to be the default behavior. 
When I have a structure like this:
```
<ContextMenuTrigger id={CONTEXT_MENU_ID}>
	<div className='container'>
		<div className='item'>
			{content}
		</div>
		<div className='item'>
			{content}
		</div>
	</div>
</ContextMenuTrigger>
```
I would like to have context menu active only on the container div and not on items inside the container. When I click on an item, I want to have default browser context menu. Is this possible?
