### ISSUE TITLE
How work with nested `ContextMenuTrigger` ?

### ISSUE THREAD

**Issue by batazor** [vkbansal/react-contextmenu#129]
## Version
2.6.3

## Steps to reproduce

```
// fileTwo
children = <ContextMenuTrigger>{...component}</ContextMenuTrigger>

// fileOne
<ContextMenuTrigger id={`contextMenu-${this.props.id}`} className={s.ContextMenu}>
     <MainPage>
             { this.props.children }
     </MainPage>
</ContextMenuTrigger>
```

## Actual Behavior

If you attach one ContextMenuTrigger nested to another ContextMenuTrigger, 
then the CSS-calculated with the offset

P.S. example https://codesandbox.io/s/vgm8LP4G0

**Comment by batazor** [comment]
I changed the structure of my components, adding `position: relative;` it's like solved the problem
@vkbansal

**Comment by batazor** [comment]
![screenshot from 2017-07-12 16-15-09](https://user-images.githubusercontent.com/1643797/28119705-788a7488-671e-11e7-8858-0bc8b752b2d4.png)

**Comment by vkbansal** [comment]
Can you provide me a reproducible code?

**Comment by batazor** [comment]
@vkbansal ok, I will try to do it shortly

**Comment by batazor** [comment]
@vkbansal I created simple example https://codesandbox.io/s/vgm8LP4G0

Click by `ChildrenJS`

**Comment by vkbansal** [comment]
Thanks for the example. I've taken a look and I'll try to work on the fix over the weekend.

**Comment by vkbansal** [comment]
Hey, So I tried to debug and the issue appears with `react-grid-layout` as it applies a `transform` on the element.

![jul-18-2017 08-24-24](https://user-images.githubusercontent.com/5930351/28298775-d41d248a-6b92-11e7-9c9a-f107d54a9a63.gif)

**Comment by vkbansal** [comment]
I've added nested example
https://vkbansal.github.io/react-contextmenu/#/nested

**Comment by travisdahl** [comment]
I don't know how useful that nested example is in a real use case. You may not have the context of the child item to perform an action on if that is a nested component.. example:

```
render() {
    return (
        <div>
            <h3>Test Menu</h3>
            <p>This demo simple usage of a context menu.</p>
            <ContextMenuTrigger id={MENU_TYPE} holdToDisplay={1000}>
              I have a list
              <ul>
                <MyListItem />
              </ul>
            </ContextMenuTrigger>
            <div>
                {this.state.logs.map((log, i) => <p key={i}>{log}</p>)}
            </div>
            <ContextMenu id={MENU_TYPE}>
                <MenuItem onClick={this.handleClick} data={{ item: 'item 1' }}>Menu Item 1</MenuItem>
                <MenuItem onClick={this.handleClick} data={{ item: 'item 2' }}>Menu Item 2</MenuItem>
                <MenuItem divider />
                <MenuItem onClick={this.handleClick} data={{ item: 'item 3' }}>Menu Item 3</MenuItem>
            </ContextMenu>
        </div>
    );
}


//in MyListItem.js

{/* START: in a real world case this would likely be in its own component which would have the context Im dealing with (e.g. listItem )*/}
<li className='well'>
    <span>right click to see the menu</span>
    <ContextMenuTrigger id={MENU_TYPE2} holdToDisplay={1000}>
        <div className='well' style={{ border: '1px solid white' }}>
            right click to see the nested menu
        </div>
    </ContextMenuTrigger>
    <ContextMenu id={MENU_TYPE2}>
        <MenuItem onClick={()=>{this.handleListItemClick(listItem.id)}} data={{ item: 'nested item 1' }}>Nested Menu Item 1</MenuItem>
        <MenuItem onClick={()=>{this.handleListItemClick(listItem.id)}} data={{ item: 'nested item 2' }}>Nested Menu Item 2</MenuItem>
        <MenuItem divider />
        <MenuItem onClick={()=>{this.handleListItemClick(listItem.id)}} data={{ item: 'nested item 3' }}>Nested Menu Item 3</MenuItem>
    </ContextMenu>
</li>
{/* END: in a real world case this would likely be in its own component which would have the context Im dealing with (e.g. listItem )*/}
```

When i try to do something like this, I get both menus. I could potentially stop propagation myself if I had access to the original event but it seems the original event is not available via `onShow`.

**Comment by ayushnawani** [comment]
@travisdahl  how did you solved it ?.  I am also facing this same issue.

**Comment by travisdahl** [comment]
@ayushnawani I ended up writing my own contextMenu component. No longer using this project
