### ISSUE TITLE
Option to Attach Context Menu to <body>

### ISSUE THREAD

**Issue by lord-xeon** [vkbansal/react-contextmenu#130]
## Version
2.6.2

## Steps to reproduce
Attach the Context Menu to a component embedded in something that uses heavy z-indexes - like a column in react-data-grid.

## Expected Behavior
ContextMenu renders above everything

## Actual Behavior
Due to z-index issues, parts of context-menu are visible, while others are below other elements.

--
I'm trying to integrate the react-contextmenu into my application which also makes use of a bunch of other react libraries, including react-data-grid.  Currently, the react-contextmenu renders it's components under the react DOM tree of the component it's under.  Is there a way to optionally say render this react-contextmenu on the <body /> element (or ideally, inside of any element of our choosing?).  This would alleviate the z-index issues I'm experiencing.

**Comment by vkbansal** [comment]
Currently there is no option to attach to any element of our choosing because there is no stable API within React itself to achieve the same.
