### ISSUE TITLE
if scroll the window, the contextmenu will not visible

### ISSUE THREAD

**Issue by jnotnull** [vkbansal/react-contextmenu#131]
I have modified the bug, please merge it, thanks: https://github.com/jnotnull/react-contextmenu/commit/774f05420905a90504a247b694d5f55fc5d851ef

## Version
1.2.0

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

**Comment by vkbansal** [comment]
Can you provide more details? this is not helpful

**Comment by sachin32** [comment]
How this will work and its merged or not

**Comment by vkbansal** [comment]
Closing due to no response
