### ISSUE TITLE
Ability to show the icon with MenuItem would be a great feature to have.

### ISSUE THREAD

**Issue by lakshya-8** [vkbansal/react-contextmenu#135]
## Version
1.2.0

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

## Expected Behavior

- ContextMenu in Google Drive is an example of expected behaviour where it shows the icon right text to menu-item text.

**Comment by vkbansal** [comment]
You are free to show any thing. You can do this.
```js
<MenuItem onClick={this.handleClick} data={{ item: 'item 1' }}>
  <Icon />
  Menu Item 1
</MenuItem>
```

**Comment by lakshya-8** [comment]
Thanks for your quick response @vkbansal .
