### ISSUE TITLE
ClickHold causing the menu to appear

### ISSUE THREAD

**Issue by dsslimshaddy** [vkbansal/react-contextmenu#137]
Left Click hold triggers the menu open.

**Comment by Amitdevelopment** [comment]
@dsslimshaddy  I am also facing the same issue. 
Can you please tell me how did you solved this issue?

**Comment by vkbansal** [comment]
https://github.com/vkbansal/react-contextmenu/blob/master/docs/faq.md

**Comment by Amitdevelopment** [comment]
Thanks !
I solved this using `holdToDisplay` .
