### ISSUE TITLE
If two grid items are there calling same component and if right clicked on one of grid item, the csm showing for both grid items, how to differentiate

### ISSUE THREAD

**Issue by sourabhlk** [vkbansal/react-contextmenu#138]
## Version
1.2.0

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

**Comment by vkbansal** [comment]
Please be more specific and provide code samples/screen shots of your issue.

**Comment by vkbansal** [comment]
Closing due to no response. Please reopen when you can provide code samples.
