### ISSUE TITLE
Prevent Default on touch screens

### ISSUE THREAD

**Issue by sabina4** [vkbansal/react-contextmenu#139]
I have a ContextMenuTrigger that wraps a checkbox. On touch screens the long press still triggers the default menu: copy/define/share...

Here is a sample of my code:
```js
<ContextMenuTrigger>
         <div>
              <Checkbox
                  checkboxClass="icheckbox_flat-blue component-checkbox"
                  increaseArea="20%"
                  label="checkbox label"
                  name="checkboxName"
                   onChange={this.handleCheckChange}
                  checked={this.state.checkboxName.checked}
               />
          </div>
 </ContextMenuTrigger>
```

...

## Version
1.2.0

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

**Comment by vkbansal** [comment]
You have not provided provided `id` to `<ContextMenuTrigger>` and also try adding `holdToDisplay Props`.

**Comment by sabina4** [comment]
i tried adding holdToDisplay it still didn't work. and i do have an id in my code i just forgot to copy it here

**Comment by vkbansal** [comment]
Can you create a reproducible demo on jsbin / webpackbin?

**Comment by sabina4** [comment]
i solved it. i removed the label from the checkbox and added a separate label that is wrapped with the trigger. i also added user-select:none to the label
