### ISSUE TITLE
When context menu is showing, right click shows the browser's context menu

### ISSUE THREAD

**Issue by willgates** [vkbansal/react-contextmenu#14]
Right click shows the context menu. When you right click again, it shows the browser's context menu. I would expect the context menu to move to where the second right click happened, instead of showing the brower's context menu.

![context-menu-right-click](https://cloud.githubusercontent.com/assets/11860584/15142006/edd6ada4-169a-11e6-93e4-b3d8263a2190.gif)

**Comment by vkbansal** [comment]
That's how it is implemented. When you are right-clicking the second time, your are actually clicking on a transparent backdrop, which is used to detect an **outside** click.

May be I can treat a right-click also as an outside click.

**Comment by vnguyen-ombud** [comment]
that would be awesome

**Comment by rudin** [comment]
+1

**Comment by ruanmer** [comment]
The following code disable the browser context menu and hide the currently active react context menu.

`import { monitor } from "react-contextmenu";

document.addEventListener('contextmenu', e => {
  e.preventDefault();

  monitor.hideMenu();
}, false);`

**Comment by kitsanapong** [comment]
@ruanmer Thanks for workaround fix :+1:

**Comment by vkbansal** [comment]
Fixed in `v1.6.0`
