### ISSUE TITLE
Couldn't install successfully

### ISSUE THREAD

**Issue by FatFatFox** [vkbansal/react-contextmenu#140]
install steps:
1. Download the master.zip
2.unzip master.zip
3.go into master path by commandline tool
4.use npm i
5.use npm run start

result:
It can be accessed ,but the contextmenu part in page couldn't show
the console shows that some css file couldn't find

**Comment by vkbansal** [comment]
Thanks for reporting. I'll take a look when I get some free time.

**Comment by vkbansal** [comment]
This should be fixed now
