### ISSUE TITLE
Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by MonkeyJumps** [vkbansal/react-contextmenu#146]
## Version
2.6.5

## Steps to reproduce
clone & npm start
## Expected Behavior
context menu should be fully functional on IE 11.540.15063.0
## Actual Behavior
Object doesn't support property or method 'assign'
bundle.js (2277,1172)

**Comment by vkbansal** [comment]
Thanks for reporting. Fixed in v2.7.0

**Comment by MonkeyJumps** [comment]
I try to run the build script but i receive loads of expected linebreaks to be 'LF' but found 'CRLF' errors. I want to build your latest source 2.7.0 and use it.

**Comment by vkbansal** [comment]
This should help https://help.github.com/articles/dealing-with-line-endings/

**Comment by MonkeyJumps** [comment]
ok thanks. Can you update the NPM repo version to match github?

**Comment by vkbansal** [comment]
My Bad. Just published it.
