### ISSUE TITLE
CSS transform: translate() on Parent Breaks Context Menu

### ISSUE THREAD

**Issue by jtheberge** [vkbansal/react-contextmenu#147]
## Version
 ^2.6.5

## Test Case
 [http://jsbin.com/mafidoc/edit?html,css,js,output](http://jsbin.com/mafidoc/edit?html,css,js,output)

## Steps to reproduce
 Apply transform: translate(x, x) on context menu's parent element

## Expected Behavior
 Context menu appears next to cursor when right-clicking.

## Actual Behavior
Context menu shifted twice as much as the parent's transform away from the cursor.

**Comment by vkbansal** [comment]
We `position: fixed` for positioning the menu and it does not work correctly when transforms are applied. This just how CSS works.

http://meyerweb.com/eric/thoughts/2011/09/12/un-fixing-fixed-elements-with-css-transforms/

**Comment by Snowcastle-Serenade** [comment]
Here's how I worked around this if it helps anyone:

1. Wrap `<ContextMenu>` with a div (let's call it `wrapper`)
2. Assign `wrapper`'s style to be `"position: fixed; top: -{parentTop}px; left: -{parentLeft}px;`
3. Set `<ContextMenu>`'s style to be `position: relative !important;`
4. Add `onShow={() => this.correctContextMenuPosition()}` to `<ContextMenu>`
5. In `correctContextMenuPosition()`:
   Use DOM selectors to find the translated parent and get its `getBoundingClientRect()`
   Use `wrapper`'s ref to set the `top` and `left` styles negative of the parent

**Comment by paulkaplan** [comment]
We had a similar issue trying to render a `ContextMenu` inside a parent that had a `transform: scale` on it. For anyone looking for a simpler solution, we just used `React.createPortal` [docs](https://reactjs.org/docs/portals.html) to place the context menu at the end of the body, which works because it is `position: fixed` anyway.
