### ISSUE TITLE
Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by MonkeyJumps** [vkbansal/react-contextmenu#149]
## Version
2.7.0

## Steps to reproduce
Load dynamic menu
right click  ContextMenuTrigger 
## Expected Behavior
ContextMenu should appear
## Actual Behavior
javascript runtime error when using ie11: Object doesn't support property or method 'includes' inside the handleShow event.

I've personally have handled this by using lodash, but I don't see that being used so i didn't want to attempt to add it.

**Comment by vkbansal** [comment]
Dynamic menu uses experimental `connectMenu.js`

see https://github.com/vkbansal/react-contextmenu/releases/tag/v2.3.1
