### ISSUE TITLE
How to get passes props in onShow?

### ISSUE THREAD

**Issue by dnish** [vkbansal/react-contextmenu#153]
Hey,
are we able to get the passed props within the onShow method? I need to show and hide some menu items when specific props are passed to the menu.

**Comment by vkbansal** [comment]
What passed props are you talking about? Props passed from `ContextMenu` to `MenuItem` or only passed to `MenuItem`.

**Comment by brusherru** [comment]
I need access to `trigger` props inside `onShow` callback, cause I want to dispatch something.
E.G. I opens a context menu on some item and I want to dispatch "SELECT_ITEM" with item id (it's a dynamical menu).
