### ISSUE TITLE
onShow and onHide in ContextMenuTrigger

### ISSUE THREAD

**Issue by miachenmtl** [vkbansal/react-contextmenu#160]
Hi, I'm using react-contextmenu in a table that utilizes another plugin. The ContextMenu component is declared near the top of the component tree, outside of the table so it won't be hidden by the table's `overflow: hidden` CSS. ContextMenuTrigger, on the other hand, is in a deeply nested component inside the table, and it's not straightforward to pass props down because of the table plugin. What I'd like is for ContextMenuTrigger to "know" when the ContextMenu is open or closed (my use case is that the context menu is triggered by left-clicking a button, and left-clicking the button when the menu is already open should close it).
I was able to get around this by looking at the source code and adding event listeners in ContextMenuTrigger for the `REACT_CONTEXTMENU_SHOW` and `REACT_CONTEXTMENU_HIDE` custom events. However, this clearly isn't an ideal solution since it's not a documented part of the API and it doesn't seem to be a very React way of doing things.
I noticed that there's an outstanding PR (#159) for adding an onShow callback to ContextMenuTrigger. Could there be an onHide one as well? I'd be willing to help with a PR, but like I said I'm not sure my approach is the way to go.

**Comment by vkbansal** [comment]
The PR you are referring to has both `onShow` and `onHide` callbacks. I'm waiting for the author to respond to my comments.
