### ISSUE TITLE
Unmet peer dependency "prop-types@^15.0.0".

### ISSUE THREAD

**Issue by stevenmusumeche** [vkbansal/react-contextmenu#162]
## Version
2.8

When using `prop-types@^15.6.0` as needed for React 16, I get the following warning when using this package.

    warning "react-contextmenu@2.8.0" has unmet peer dependency "prop-types@^15.0.0".

Can you update the peer dependencies to support the latest `prop-types` package?

**Comment by vkbansal** [comment]
According to https://semver.npmjs.com/
`prop-types@^15.0.0` should allow `prop-types@^15.6.0`
<img width="1603" alt="screen shot 2017-11-15 at 11 28 26 am" src="https://user-images.githubusercontent.com/5930351/32821188-2a20b3ce-c9f8-11e7-9139-04d22d63e72f.png">

**Comment by stevenmusumeche** [comment]
yarn 1.2.1
