### ISSUE TITLE
Menu should left or right align, not default left

### ISSUE THREAD

**Issue by ninjaofawesome** [vkbansal/react-contextmenu#164]
## Version
1.2.0

## Overview
This menu is quite handy, except for one flaw- the menu always aligns in one direction- towards the left.  For my use case, I need the menu to align to the right.

Similarly to implementing a left click action instead of a right one, there should be an option to select menu orientation.  There was nothing in the documentation on how this may be implemented.

## Steps to reproduce
- Integrate menu into a project, any type
- Click on button
- See menu with left alignment.

## Expected Behavior
- This meets the expected behavior, however the anticipated behavior is to change the orientation.

## Actual Behavior
- Works as anticipated.

**Comment by vkbansal** [comment]
This behaviour is based on how native context-menu works.

I'm ready to accept a PR with the requested feature.
