### ISSUE TITLE
Context menu appearing under surrounding Material UI Chip component

### ISSUE THREAD

**Issue by zelanter** [vkbansal/react-contextmenu#165]
Hi,

this is a very specific case and here might not be the proper place to post it, but still thought it would be interesting to see if anyone here would have ideas, suggestions to get around the issue I am running into:

I added react-contextmenu on Material UI Chip component, it's actually a list of Chips, side by side, and each can trigger the context menu. However, when right clicking, the menu appears under surrounding chips. Is there any known way to force it to be on top? Is it achievable through CSS? How much we can customize style for react-contexmenu does not seem to be in api documentation.

Thanks

**Comment by vkbansal** [comment]
Have you tried increasing the `z-index`?

**Comment by zelanter** [comment]
Adding z-index to style of main contextMenu style? Tried it now, did not seem to work. Tried for MenuItem too.

Thanks

**Comment by zelanter** [comment]
@vkbansal I saw some style related updates lately, will that potentially make it easier to get around this issue? 

Thanks

**Comment by vkbansal** [comment]
Can you make a JSfiddle example? It will help in debugging
