### ISSUE TITLE
onMouseMove event handler is not properly registered when MenuItem's are abstracted into another component.

### ISSUE THREAD

**Issue by mgummelt** [vkbansal/react-contextmenu#169]
This is due to this function: https://github.com/vkbansal/react-contextmenu/blob/e655e22f561b6eb80d9c4708c67121b3e5a9e60a/src/AbstractMenu.js#L115 which adds a `onMouseMove` handler to `ContextMenu`'s immediate child, which must be a `MenuItem` to work properly, but is not when the `MenuItem` list is abstracted into a separate component.

## Version
2.8.0

## Steps to reproduce
Wrap `MenuItem`s in another component, e.g.:

```
function Main(props) {
  <ContextMenu>
    <MenuItems />
  </ContextMenu>
}

function MenuItems(props) {
  return [<MenuItem />, [MenuItem />]
} 
```
## Expected Behavior
Mousing over the `MenuItem` property appends the `react-contextmenu-item--selected` css class.

## Actual Behavior
It doesn't.

**Comment by vkbansal** [comment]
I cannot think of a fix for this. Do you have a solution?

**Comment by mgummelt** [comment]
Not off the top of my head.  It might be helpful to add some error checking code that fails early in this case.  I spent a bit of time debugging.

**Comment by PrinceIKhanna** [comment]
I have the same issue now, and it is not working. Menu item click is not working when wrapped inside another component.
