### ISSUE TITLE
Examples page is not working anymore

### ISSUE THREAD

**Issue by dana2208** [vkbansal/react-contextmenu#178]
Hi,

When clicking on examples we are redirected to 404 page.
Could you please fix this?

Thank you!

**Comment by vkbansal** [comment]
It is working fine for me. Can you give me the link at which you are seeing 404?

**Comment by dana2208** [comment]
https://github.com/vkbansal/react-contextmenu/blob/master/docs/examples

**Comment by vkbansal** [comment]
fixed it. thanks for reporting
