### ISSUE TITLE
Retrieving instance and/or state of target

### ISSUE THREAD

**Issue by jameslai** [vkbansal/react-contextmenu#18]
A frequent use-case I'm experiencing is the need to access the instance of the target being right-clicked. It appears react-contextmenu is so laser focused on proving data, it doesn't have a method to provide the instance of the react component being right-clicked. This is especially relevant when I would like to modify the state of the target.

Is there a plan to add this feature or have I missed something?

**Comment by vkbansal** [comment]
Can you explain me your use case??

**Comment by jameslai** [comment]
Absolutely. For example, I have an item in a list which, when double clicked, should enter a state to allow for editing the name of that item. Basically I swap out a `span` with an `input` for inline editing. The component's render method observes `this.state.editing`, and if set to `true`, renders the `input`.

When the item is double clicked, `onDoubleClick` calls a method (`startEditing`) on that component which updates the state to set `editing` to `true`. I would also like the user to have the option of right clicking the item and selecting "Rename" (there are other context menu items as well, but this serves as a good example). This is where the problem comes in.

`ContextMenuLayer`'s `configure` method only exposes the `props` of the component. I cannot access methods from the instance of that object. I also cannot pass `startEditing` to the component from a parent component, as `ContextMenuLayer` does not expose the context of the instance of the component to bind `startEditing` to so it can successfully access `this.state` on the relevant component.

Any help is appreciated.

**Comment by maartenscholz** [comment]
+1

**Comment by vkbansal** [comment]
Please checkout the changes in master branch and see simple menu example.

If it satisfies your needs, let me know.

**Comment by alolis** [comment]
@jameslai , did you manage to solve this? can you please provide an example?

**Comment by vkbansal** [comment]
I have not be able to solve this. Any help would be appreciated.

**Comment by mreishus** [comment]
Hmm, I have the same problem, I'm about to add something to my redux store that says which item I'm renaming.  Don't really want to do this... :/

**Comment by vkbansal** [comment]
I've released `v2.0.0-alpha.1` with this feature. Do check it out. Any feedback is welcome 😃

**Comment by barbalex** [comment]
@vkbansal: as it is not explained in the readme: could you please explain how it is possible to access the element that was right clicked?

**Comment by barbalex** [comment]
@vkbansal sorry - I did not read the readme well enough - it _IS_ explained
