### ISSUE TITLE
Allow props to be passed to handleContextClick when showing menu from code

### ISSUE THREAD

**Issue by will-hart** [vkbansal/react-contextmenu#180]
I have an external component library where I'm trying to provide different context menus for different types of child components. I am unable to edit the library to add in `ContextMenuTriggers` on all the child components.

I can show the correct menu by declaring `ContextMenuTriggers` at a higher level outside of the library, and calling the `handleContextClick()` function on the triggers. The library components use a callback to say when they need a context menu to be displayed. The basic structure looks like this:

    const handleShowContext = (event, type) => {
        if (type === 'menu1') this.menu1.handleContextClick(event)
        else if (type === 'menu2') this.menu2.handleContextClick(event)
    }

    const renderComponent = () => (
        <div>
            <ContextMenuTrigger id='menu1' ref={cm => this.menu1 = cm}>{' '}</ContextMenuTrigger>
            <ContextMenuTrigger id='menu2' ref={cm => this.menu2 = cm}>{' '}</ContextMenuTrigger>
            <MyLibraryComponent onShowContext={handleShowContext} />
        </div>
    );

The internal structure of the library looks a bit like this:

    <MyLibraryComponent>
        <A onContextMenu={e => this.props.handleShowContext(e, 'menu1')} />
        <B onContextMenu={e => this.props.handleShowContext(e, 'menu2')} />
    </MyLibraryComponent>

This works OK, however I don't have a way to pass the id of the component requesting the context menu into the menu itself. 

Ideally I would be able to pass arguments to `handleContextClick` like this:

    handleShowContext = (event, type, id) => {
        if (type === 'menu1') this.menu1.handleContextClick(event, { id })
        else if (type === 'menu2') this.menu2.handleContextClick(event, { id })
    } 

I thought that this could be implemented by only changing two lines:

[L91](https://github.com/vkbansal/react-contextmenu/blob/59731690e84dfaba8b8319df2d0b41d9281d5e03/src/ContextMenuTrigger.js#L91) change `handleContextClick = (event) =>` to `handleContextClick = (event, additional) =>`

[L102](https://github.com/vkbansal/react-contextmenu/blob/59731690e84dfaba8b8319df2d0b41d9281d5e03/src/ContextMenuTrigger.js#L102) from `callIfExists(this.props.collect, this.props)` to `callIfExists(this.props.collect, Object.assign({}, additional || {}, this.props))`

However the props aren't updated when the menu is shown, so this doesn't work. Any thoughts on this?

**EDIT** [Related SO Question?](https://stackoverflow.com/questions/42659634/create-react-context-menu-on-the-fly)

**Comment by vkbansal** [comment]
Does not the SO answer solve your issue?

**Comment by will-hart** [comment]
I'm not 100% sure, I'll take a look :+1:

**Comment by jaepd** [comment]
This is an issue for me too and that SO question's answer doesn't solve it, but the proposed solution would.
