### ISSUE TITLE
Packaging changes in 2.9.2

### ISSUE THREAD

**Issue by eddies** [vkbansal/react-contextmenu#181]
## Version
2.9.2

## Description

Between (at least) 2.8.0 and 2.9.1, react-contextmenu releases have included `dist`, `es6`, `modules`, and `public` directories. However, with 2.9.2, these are gone, but we now have `examples` and `tests`.

I had a reference to `public/styles.css` that broke when I updated, so I'm just looking to see if that will no longer be a stable reference.

Thanks!

**Comment by vkbansal** [comment]
From [unpkg.com](https://unpkg.com/react-contextmenu@2.9.2/), I see `dist`, `docs`, `es6`, and `modules` are all present.

`public` was never meant to be included. It is used only for deploying docs.

And going forward `src` and `docs` will also be removed.

**Comment by eddies** [comment]
My bad--I had already downgraded to 2.9.1 when I made this issue and so just downloaded 2.9.2 from the releases tab (https://github.com/vkbansal/react-contextmenu/archive/v2.9.2.tar.gz) when cataloging the changed directories. (So indeed public is no longer present and examples and tests are not present in npm).
