### ISSUE TITLE
How can you add a title to your context menu?

### ISSUE THREAD

**Issue by maasha** [vkbansal/react-contextmenu#182]
I have done this before with jquery contextmenu ala this where it says "New Group":

<img width="229" alt="screen shot 2018-01-02 at 20 27 47" src="https://user-images.githubusercontent.com/1158057/34496845-7b4e4062-effb-11e7-88a3-86bb608d82e9.png">

**Comment by vkbansal** [comment]
You can render anything within `<ContextMenu/>`

**Comment by maasha** [comment]
Ah! How about including an example of that in the demo?
(also, `divider` is not documented in the API)
