### ISSUE TITLE
Broken handleKeyNavigation

### ISSUE THREAD

**Issue by koutsenko** [vkbansal/react-contextmenu#184]
## Version
2.9.2

## Test Case
Your test fiddle not work. So, by words. I created a menu and opened it, but keyboard arrow keys not work. Application crashing, AbstractMenu.js::L112. "child" variable contains an text value provided to MenuItem as jsx children. But at line 112 , library trying to access child.props.children variable. 

Code
![screen6](https://user-images.githubusercontent.com/529293/34771529-e6755bf8-f615-11e7-8ee6-124b9f54c72a.png)

Error
![screen7](https://user-images.githubusercontent.com/529293/34771531-e980352a-f615-11e7-8d60-942374642d5e.png)

## Suggestion
Please fix the internal **handleKeyNavigation** method and add "disableHotkeys" property to ContextMenu .

**Comment by koutsenko** [comment]
@codeart1st can you take a look?

**Comment by koutsenko** [comment]
Nevermind. 
I switched to material-ui-next Menus (in -next, they can be relatively positioned) + oncontextmenu event/

**Comment by codeart1st** [comment]
I will look into it next time

**Comment by rolandgnm** [comment]
![image](https://user-images.githubusercontent.com/819527/45822585-2401a400-bd2f-11e8-9c52-87a7323febe9.png)
Guys, I've seen the runtime always enter this if statement regardless of index apparently be greater than zero. I'd like reopen this issue so someone can have a look at this. Thanks a lot!
