### ISSUE TITLE
isMounted error

### ISSUE THREAD

**Issue by pouu69** [vkbansal/react-contextmenu#187]
## Version
1.6.3

## Problem
If i click right mouse , below show error

`Warning: Modal: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.`

**Comment by vkbansal** [comment]
v1.6.3 is no longer supported. Please upgrade to v2 if possible.

**Comment by pouu69** [comment]
plz supported IE 10  in v2

**Comment by pouu69** [comment]
Perhaps there is an error in the react-overlay Modal.

**Comment by vkbansal** [comment]
I'm sorry. Since this is an open-source project, I do not have resources to support old browsers.

You are free to fork this project and use it.

**Comment by shift-keshav-pudaruth** [comment]
IE 10 is no longer officially supported.

https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support
