### ISSUE TITLE
PropTypes and transform-react-remove-prop-types

### ISSUE THREAD

**Issue by faiwer** [vkbansal/react-contextmenu#189]
Hello. There is one usefull babel plugin called `transform-react-remove-prop-types`. It removes excess `PropTypes` from production builds and decreases the build file size. But it can't work with `react-contextmenu` package because it (`react-contextmenu`) works with `propTypes` fields in runtime.

e.g.:
```js
var ignoredTriggerProps = [].concat(_toConsumableArray(Object.keys(ContextMenuTrigger.propTypes)), ['children']);
```
and another similar code blocks. Could you please amend this part of `react-contextmenu`? I mean the code above can check the fact of providing propTypes in runtime. 

P.S. `transform-react-remove-prop-types` is a common used plugin. Many guides for optimizing your webpack recommend it. It can save you extra 5-10% of filesize.

> Remove React propTypes from the production build, as they are only used in development. You can save bandwidth by removing them

from [page](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types)

**Comment by vkbansal** [comment]
I'm planning to move to typescript and remove propTypes anyways.
