### ISSUE TITLE
Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by ruanmer** [vkbansal/react-contextmenu#19]
I just updated to 1.6.0 version and this error pop out. 

"Cannot read property 'parentNode' of undefined".

As I saw, its related to [this changes](https://github.com/vkbansal/react-contextmenu/commit/0e8ea32e2aa65b33ab9ed143a46fff40d2b0735a). **Line 41**

**Comment by vkbansal** [comment]
Thanks for reporting
