### ISSUE TITLE
Readme Has Invalid Example

### ISSUE THREAD

**Issue by machineghost** [vkbansal/react-contextmenu#190]
## Version
1.9.1

## Test Case
None

## Steps to reproduce
Visit GitHub front page

## Expected Behavior
Example actually works.

## Actual Behavior
The example violates the library's own rules, because it includes:

    <MenuItem data={"some_data"}

First off, you don't need `{}` to pass a string property in React, but more importantly you can't pass a string as data in `react-contextmenu`; if you try you get a `PropType` warning: "Failed prop type: Invalid prop `data` of type `string` supplied to `MenuItem`, expected `object`."

The example should be something more like:

    <MenuItem data={{some: `data`}}

Obviously this isn't the most important bug, but still,  do you really want new users' first experience with the library to be a "you just did something wrong" warning when all they did was copy/paste the example code?

**Comment by vkbansal** [comment]
Can you open a PR?

**Comment by hybridwebdev** [comment]
Can you not just fix this issue yourself, as you are the original dev? Expecting people to fix your plugin is just lazyness.

**Comment by vkbansal** [comment]
@hybridwebdev What is your issue? Why are you so pessimistic?
I have a full time job and I maintain this package in my free time.
I ask people to open a PR, so that they can start contributing to open-source and not due to laziness.

**Comment by machineghost** [comment]
@hybridwebdev Asking for a PR is pretty standard OSS etiquette (even for small fixes like this).

@vkbansal Unfortunately I'm a bit swamped ATM, but when I have some time I'll try and submit one.

**Comment by vkbansal** [comment]
@machineghost No issues. Take your time.

**Comment by Alek-S** [comment]
@machineghost and @vkbansal 

Created pull request #208 for this. If you could review that PR to confirm that's correct. Basically just a readme update.
