### ISSUE TITLE
Default Styles Should Have a Z-Index of at Least 2 (Maybe 9999 to be Safe?)

### ISSUE THREAD

**Issue by machineghost** [vkbansal/react-contextmenu#192]
## Version
1.9.1

## Test Case
None

## Steps to reproduce
Create any context menu using the recommended default styles, including:

    .react-contextmenu.react-contextmenu--visible {
      opacity: 1;
      pointer-events: auto;
    }

## Expected Behavior
The context menu won't get hidden behind other elements (and potentially appear to not work at all) when using author-recommended styles.

## Actual Behavior

If you add the `<ContextMenu`> tag before any other elements (at the same DOM hierarchy level), those elements will cover up the menu ... even with the recommended styles.  This can easily be prevented with a `z-index: 2` style, although since the context menu should really appear above just about any other element, a style of `z-index: 9999` might be safer.

The specific change I would propose (and can easily submit as part of a PR, if desired) is:

    .react-contextmenu.react-contextmenu--visible {
      opacity: 1;
      pointer-events: auto;
      z-index: 9999; /* Ensure context menu always appears on top */
    }

**Comment by vkbansal** [comment]
Can you open a PR?

**Comment by Alek-S** [comment]
PR opened.
