### ISSUE TITLE
Positioning Breaks When Not Relative to Window

### ISSUE THREAD

**Issue by skipjack** [vkbansal/react-contextmenu#193]
## Version

1.9.1

## Test Case

https://jsfiddle.net/Luktwrdm/129/

## Steps to reproduce

1. Right click the positioned `#container`.
2. Notice the offset position of the context menu.

## Expected Behavior

Parent styling won't affect context menu positioning.

## Actual Behavior

Certain parent styling, i.e. [anything](https://developer.mozilla.org/en-US/docs/Web/CSS/position#absolute) that will cause `position: fixed` not to be relative to the viewport, will throw off the positioning because it is computed based on `innerWidth` and `innerHeight`:

https://github.com/vkbansal/react-contextmenu/blob/master/src/ContextMenu.js#L151-L179

I ran into this issue when using `react-virtualized` as it's containers use the `will-change: transform` declaration. Overriding the `top` and `left` fields somewhat fixed the issue but this means the menu will only be positioned based on the nearest relative parent rather than `x` and `y` of the click event.

I'm not sure what the fix for this would be. Maybe there's a way to always find the relative container and use that instead of always using `window`? Would be happy to submit a PR once we talk through a fix.

**Comment by skipjack** [comment]
[`HTMLElement.offsetParent`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/offsetParent) looked promising but it only seems to return `null` for the `position: fixed` menu.

**Comment by vkbansal** [comment]
Similar to https://github.com/vkbansal/react-contextmenu/issues/147

**Comment by codyparker** [comment]
I came across this issue today after adding in [react-virtualized](https://github.com/bvaughn/react-virtualized). I was able to fix it by using [react-portal](https://github.com/tajo/react-portal). I just wrapped my ContextMenu in the Portal component and the menu displayed in the correct position.

```html
<Portal>
  <ContextMenu>
   ...
  </ContextMenu>
</Portal>
```
