### ISSUE TITLE
Context menu doesn't show during test in PhantomJS

### ISSUE THREAD

**Issue by willgates** [vkbansal/react-contextmenu#20]
My (previously successful) tests are now failing because the context menu isn't showing on right-click in PhantomJS. In [contextmenu-layer.js#L79-80](https://github.com/vkbansal/react-contextmenu/blob/master/src/contextmenu-layer.js#L79-80) `event.touches` doesn't exist when running these tests hence why they fail.

Could you please change to: `const xPos = event.clientX || (event.touches && event.touches[0].pageX),
                    yPos = event.clientY || (event.touches && event.touches[0].pageY);`

**Comment by vkbansal** [comment]
Can you open a PR?
