### ISSUE TITLE
Why click on menu item which contains submenu will close whole context menu

### ISSUE THREAD

**Issue by AndySu0216** [vkbansal/react-contextmenu#200]
## Version
2.9.1

## Test Case
https://vkbansal.me/react-contextmenu/#/submenus

## Steps to reproduce
1. use the example submenu
2. click on "A SubMenu" item
3. whole context menu close

## Expected Behavior
keep context menu open
## Actual Behavior
close

this should work on version 2.8.0.

**Comment by LiiXi** [comment]
I think this is due to https://github.com/vkbansal/react-contextmenu/pull/171/files#diff-fac7eaa4f7d20c1dfe49b85192280d69R174

**Comment by Alek-S** [comment]
#204 resolved this. Can probably be closed out.
