### ISSUE TITLE
FAQ example showing how to manually handle click event does not work

### ISSUE THREAD

**Issue by hybridwebdev** [vkbansal/react-contextmenu#202]
I don't expect i'll get a helpful reply from the dev, as based on other issues, he's been all but helpful to people but here goes...

As per your FAQ example showing how to manually handling menu trigger via a left click, the example only partially works. I can get the manual click handler to work just fine, howerver there doesn't seem to be a way to actually manually disable right click from triggering as well. I've read the api/faq docs and looked at the examples, but there's nothing mentioning how to do this short of adding disable={true} to the context menu trigger component. However doing so also attaches that prop to the manually triggered event, and you can not modify the props, even using a re-assignment.

**Comment by vkbansal** [comment]
Form what you are saying I understand that you want to disable right-click completely, right?

**Comment by hybridwebdev** [comment]
yes

**Comment by vkbansal** [comment]
> I don't understand why this was coded to use the right click at all.

This is a [context-menu](https://en.wikipedia.org/wiki/Context_menu) and by definition it is meant to be used on right-clicks only.

If you want to use menus on left click, there are other components that are more suitable than this component.

**Comment by hybridwebdev** [comment]
That is the EXACT attitude I was talking about in my original post. If you're unwilling to help users with issues, why post a public github? Can you please address the original issue track, as it is in fact fully valid. As per another issue submitted, you have inconsistent documentation.

Also, telling someone to "use something else" when they've spent hours trying to work with your plugin is just plain rude and dismissive.

**Comment by vkbansal** [comment]
> If you're unwilling to help users with issues, why post a public github?
I cannot control how the users of this plugin are using it. If someone is using it in a way which is the not intended by the author, then it's not my responsibility.

> Also, telling someone to "use something else" when they've spent hours trying to work with your plugin is just plain rude and dismissive

I did not ask you to use this plugin. It's you, who chose to use it.

**Comment by hybridwebdev** [comment]
Why submit a public code base if you have no intention of supporting/maintaining it? That goes against the very nature of git hub. If you don't want to support it, you should probably make this repository private so others don't waste their time trying to get it to work. I'd wager that if you do professional development, you'd expect people NOT to waste your valuable time, so why do you think it's okay you waste other peoples time? Especially when you can't be bothered to provide proper documentation.

**Comment by vkbansal** [comment]
> Why submit a public code base if you have no intention of supporting/maintaining it? 

I've open sourced this more than 2 years ago and I cannot maintain it anymore because I do not have time and resources.

> That goes against the very nature of github.
You have wrong understanding of GitHub then. It's meant for sharing code and not support-center for it.

> If you don't want to support it, you should probably make this repository private so others don't waste their time trying to get it to work.

 I've mentioned in the `README` that I'm looking for maintainers. That should have been a hint for you.


> I'd wager that if you do professional development, you'd expect people NOT to waste your valuable time, so why do you think it's okay you waste other peoples time?

I agree that I do not want others to waste my time, but a part of being a developer is evaluating libraries for the use case. If one does not fit your use case, move on the next and not to crib about it.
If nothing works, write your own. (This is how I work at-least.)


> you can't be bothered to provide proper documentation.

You are the only one out of thousands of users of this library who does not understand the documentation. If you have problem with it, help in improving it instead of behaving like a jerk.
