### ISSUE TITLE
Add ability to customize arrow in SubMenu

### ISSUE THREAD

**Issue by ipanasenko** [vkbansal/react-contextmenu#203]
Would be amazing to have ability to customize arrow in submenu with React component or node. Currently it's only possible to do with css

**Comment by vkbansal** [comment]
What do you want achieve? Please give an example, so that I can help you.

**Comment by ipanasenko** [comment]
We have a list of svg icons as react components, and would like to specify one of them as arrow. While it's technically possible to do `:after { content: url("path/to/icon.svg") }`, it doesn't seem ideal.

Do you think it's worth implementing?

**Comment by vkbansal** [comment]
Have you tried using `title` prop on `SubMenu`? It accepts any React component.

**Comment by ipanasenko** [comment]
Yes, title seems to work. Thanks!

**Comment by akrueger90** [comment]
Hey, I tried to pass a React Component as title. The component is displayed (text and glyph), but the default arrow is still visibile, is there a supported way to hide this?

title component
`<React.Fragment>
            <Typography>{label}</Typography>
            <ListItemIcon>
                <Glyphicon glyph="chevron-right" />
            </ListItemIcon>
        </React.Fragment>;`

rendered: 
![Bildschirmfoto 2019-10-23 um 11 01 36](https://user-images.githubusercontent.com/55091298/67376486-822d3600-f584-11e9-8424-14d56c48eed6.png)
