### ISSUE TITLE
Firefox Web-Extension, Context-Menu closing on enter

### ISSUE THREAD

**Issue by WyntersAU** [vkbansal/react-contextmenu#205]
## Version
v2.9.2

## Test Case
https://github.com/WyntersAU/rutorrent-remote/issues/2

## Steps to reproduce

1. Clone https://github.com/WyntersAU/rutorrent-remote/tree/rewrite
2. Install the dependencies
`npm init`
3. Build
`npm run build`
4. Add as developer extension in either Chrome or Firefox.
5. Right-click and enter the context menu.

## Expected Behavior
The context-menu stays open once entered and is able to click the Menuitem's

## Actual Behavior
The context-menu closes upon entering.

## Side Notes
This issue does not appear in Chrome 65.0.3325.181, while in Firefox 59.0.1 it occurs.
As a side note, upon opening the generated content from webpack [remote.html](https://github.com/WyntersAU/rutorrent-remote/blob/rewrite/extension/remote.html) no issue occurs within the browser window, only when it is loaded as a web-extension this issue is prominent. 

Wrapping the [ReactTable](https://github.com/WyntersAU/rutorrent-remote/blob/rewrite/src/remote.js#L151) element in a ContextMenuTrigger, has no effect and the "Actual Behavior" outline still occurs.

**Comment by vkbansal** [comment]
@WyntersAU Thanks for reporting the issue.

I'm not well versed with building extensions for browsers and also I'm super busy with my job.

I'll try my best to solve this whenever I find some time. But any kind of help from you will be appreciated.

**Comment by WyntersAU** [comment]
@vkbansal An update on the issue.

Upon adding a couple of `console.log`'s to "\es6\ContextMenu.js", I noticed `_this.handleShow` and `this.handleHide` are immediately both called, in aforementioned order. This behavior does not happen in Chrome or viewing the compiled webpack HTML in the browser. 

Will update more soon.

**Comment by WyntersAU** [comment]
@vkbansal I have identified the issue.

The problem is caused on [Line 89 of /src/ContextMenu.js](https://github.com/vkbansal/react-contextmenu/blob/master/src/ContextMenu.js#L89) AND [Line 91 of /src/ContextMenu.js](https://github.com/vkbansal/react-contextmenu/blob/master/src/ContextMenu.js#L91).

Once I fashion a proper resolution that does not break the functionality within each scenario I will submit a Pull Request.
