### ISSUE TITLE
Want to maintain the repository

### ISSUE THREAD

**Issue by tearsofphoenix** [vkbansal/react-contextmenu#210]

**Comment by vkbansal** [comment]
Do you have any experience of maintaining any Open source projects?

**Comment by vkbansal** [comment]
Good to hear about your professional career 👍 
But I wanted to know about Open source contributions.

**Comment by tearsofphoenix** [comment]
Not contributed much to widely known open source repositories, only some open source post-quantum cryptography project on github.
