### ISSUE TITLE
Why is "children" a required property of ContextMenuTrigger?

### ISSUE THREAD

**Issue by mgummelt** [vkbansal/react-contextmenu#214]
https://github.com/vkbansal/react-contextmenu/blob/master/src/ContextMenuTrigger.js#L12

It doesn't seem like it should be.  I want to wrap a childless React component in the ContextMenuTrigger.

**Comment by vkbansal** [comment]
I guess that makes sense. Will you be willing to open a PR with the change?

**Comment by rootid** [comment]
@mgummelt : is your custom component accept PropTypes?
