### ISSUE TITLE
How to close react-context menu on document scroll?

### ISSUE THREAD

**Issue by ashishyadav0019** [vkbansal/react-contextmenu#215]
Thanks for the awesome context menu.

I have opened the context menu on elements which are inside a scroll able **div**.
Now i want to close the context Menu when I scroll the **div**.
Please help
![demo](https://user-images.githubusercontent.com/31069071/40643068-7c2e5472-633c-11e8-9c9e-0c779c3838e3.gif)

**Comment by vkbansal** [comment]
You can add a scroll listener on the element and call `hideMenu` from `react-contextmenu/lib/actions`

**Comment by ashishyadav0019** [comment]
Ok lemme try

**Comment by ashishyadav0019** [comment]
Thanks alot it worked

**Comment by FruitAndAShape** [comment]
This worked for me...

`import { hideMenu } from "react-contextmenu"`
