### ISSUE TITLE
Popup is triggering when horizontal scrolling to either end of an agGrid

### ISSUE THREAD

**Issue by davidmgarrett** [vkbansal/react-contextmenu#218]
<ContextMenuTrigger id="gridContextMenu">
                <div style={{height: '500px'}} className="ag-fresh">
                    <AgGridReact
                        columnDefs={this.columnDefinitions}                            
                    />
                </div>
            </ContextMenuTrigger>
            <ContextMenu id="gridContextMenu">
                <MenuItem>
                    <Icon name="bolt"/>Permissions
                </MenuItem>
            </ContextMenu>

**Comment by ashishyadav0019** [comment]
It's because the popup get's triggered after longpress also.. M too facing same issue

**Comment by davidmgarrett** [comment]
I resolved it by placing the agGrid outside the trigger and instead calling it directly:


class OrdersTable extends Component {

    cellContextMenu = (e) => {
        //prevent default behavior
        e.event.returnValue = false;
        this.showContextMenu(e.event);
    }

    registerContextMenuTrigger = (trigger) => {
        this.contextMenuTrigger = trigger;
    }

    showContextMenu = (e) => {
        if (this.contextMenuTrigger) {
            this.contextMenuTrigger.handleContextClick(e);
        }
    };

    render() {

        return (
            <div>

                <div style={{height: '500px'}} className="ag-fresh">
                    <AgGridReact
                        …
                        onCellContextMenu={this.cellContextMenu}
                    />
                </div>

                <ContextMenuTrigger id="gridContextMenu" ref={this.registerContextMenuTrigger}>
                    {/* requires children */}
                    <div/>
                </ContextMenuTrigger>

                <ContextMenu>
                    …
                </ContextMenu>
            </div>
        );
    }
}
