### ISSUE TITLE
ES6 classes

### ISSUE THREAD

**Issue by valentinvichnal** [vkbansal/react-contextmenu#22]
Hi, is this works with Components using ES6 classes?
I tried to make it work but it is hard to understand without an example.

Using the old React.createClass syntax again in new projects switched to es6 classes is not very elegant.

**Comment by vkbansal** [comment]
Yes this will work irrespective of whether you use es6 classes or `React.createClass`.

Please see the examples folder

**Comment by valentinvichnal** [comment]
First I tried to extend but `ContextMenuLayer("indentifier", (props) => props)(Component)` works fine!
Thanks, awesome project!
