### ISSUE TITLE
dynamic MenuItem

### ISSUE THREAD

**Issue by owcc** [vkbansal/react-contextmenu#225]
Good component first!
how can I dynamic set visible or clickable of each menu items? perhaps `ContextMenuTrigger` should receive a function children with data which use to set item's state? something like this
```js
<ContextMenuTrigger>
    {(state) => {
        const items = [
            <MenuItem key="copy">Copy</MenuItem>,
            <MenuItem key="paste" disabled={!state.canPaste}>Paste</MenuItem>
        ]
        if (state.canCut) items.push(<MenuItem key="cut">Cut</MenuItem>)
        return items
    }}
</ContextMenuTrigger>
```
or there are some other way I missed to get this?

**Comment by daniellizik** [comment]
@owcc You can do this with the current api using `connectedMenu` to pass some props to the menu
