### ISSUE TITLE
Ctrl key modifier should open native context menu

### ISSUE THREAD

**Issue by carlosfpo** [vkbansal/react-contextmenu#240]
## Version
1.9.1

## Test Case
https://jsfiddle.net/Luktwrdm/54/

## Steps to reproduce
Press right click on the trigger with ctrl key pressed

## Expected Behavior
Open the native context menu instead of our custom context menu

## Actual Behavior
Opens the custom component content menu

**Comment by vkbansal** [comment]
You are welcome to open a PR with the proposed change
