### ISSUE TITLE
Allow ContextMenuTrigger id prop to be of type number

### ISSUE THREAD

**Issue by sambokai** [vkbansal/react-contextmenu#246]
I was surprised to see that ContextMenuTrigger wants a string for its unique id prop. I think it should also, if not only, allow numbers.

**Comment by vkbansal** [comment]
The TypeScript definitions was provided by a contributor. I do not have any idea why this decision was made. 

You can open a pull-request with the required change?

**Comment by sambokai** [comment]
It's not the typescript but the propTypes:
https://github.com/vkbansal/react-contextmenu/blob/master/src/ContextMenuTrigger.js#L11

They were [added by you ](https://github.com/vkbansal/react-contextmenu/commit/12752e2d6be868c67a83923f97416eef64675074#diff-8c52c6cf66a1c629f586678b831921a2).

I opened the issue for discussion, before writing a change, since this is a design decision.

**Comment by vkbansal** [comment]
Oh. Sorry for the confusion. Yeah number can also be used for id.

You are welcome to open a PR.

**Comment by sambokai** [comment]
I'm busy right now, but will keep it in my mind for when i have a few hours. Let's keep the issue open, in case someone else wants to do this. 

You could label this issue as beginner friendly to attract devs.

**Comment by nfvs** [comment]
What's the motivation for allowing numeric IDs? DOM element IDs are always strings, so this seems like a weird request.

https://developer.mozilla.org/en-US/docs/Web/API/Element/id

**Comment by sambokai** [comment]
I'm more used to numeric ids, but you're raising a good argument.
