### ISSUE TITLE
Prevent deselection of selected text when click on the menu item.

### ISSUE THREAD

**Issue by dholakiyaankit** [vkbansal/react-contextmenu#249]
## Version
1.9.1

## Steps to reproduce

So, I have been using the context-menu from many months now, I am using it at different places getting success with each and everything, Now, I have one common context-menu for entire website consists of undo,redo, cut,copy, paste.

This is my menu
```

 { text: UIPagesResources.CxBuilder.BUTTON_UNDO, value: "undo", category: "BrowserMenu", callingMethod: "BrowserMenu()", icon: "fa fa-fw fa fa-undo" },
{ text: UIPagesResources.CxBuilder.BUTTON_REDO, value: "redo", category: "BrowserMenu", callingMethod: "BrowserMenu()", icon: "fa fa-fw fa fa-redo-alt" },
{ text: "Divider", isDivider: true },
{ text: UIPagesResources.CxBuilder.BUTTON_CUT, value: "cut", category: "BrowserMenu", callingMethod: "BrowserMenu()", icon: "fa fa-fw fa fa-cut" },
{ text: UIPagesResources.CxBuilder.BUTTON_COPY, value: "copy", category: "BrowserMenu", callingMethod: "BrowserMenu()", icon: "fa fa-fw fa fa-copy" },
{ text: UIPagesResources.CxBuilder.BUTTON_PASTE, value: "paste", category: "BrowserMenu", callingMethod: "BrowserMenu()", icon: "fa fa-fw fa fa-paste" },

```

This is trigger when clicked on the menu item

```
switch (data.value) {
                    case "undo":
                        document.execCommand("undo");
                        break;
                    case "redo":
                        document.execCommand("redo");
                        break;
                    case "cut":
                        document.execCommand("cut");
                        break;
                    case "copy":
                        document.execCommand("copy");
                        break;
                    case "paste":
                        document.execCommand("paste");
                        break;
                    default:
                        break;
                }
```

The real problem is now, when user selects any text in the browser lets say 'abc' and then right click the menu opens and then he clicks on the copy. the copy command executes but selection of 'abc' disappears. so, in my clipboard I have empty string.  I am not sure this is duplicate issue but I can not find any hint from the previous issues.

## Expected Behavior
It should copy the selected text to the clipboard.
## Actual Behavior
It deselects the selected text and nothing happens.

**Comment by dholakiyaankit** [comment]
@vkbansal Can you please check this?

**Comment by vkbansal** [comment]
I can't sorry. I'm on Vacation.

**Comment by dholakiyaankit** [comment]
@vkbansal can you guide me who can help me to find out where is the problem?

**Comment by AntonVoltchok** [comment]
@dholakiyaankit could you store the selected text in your components state? In the click handler, have it first save the text to state and then have the menu open:
Then when the user clicks the menu option copy, you can pass text stored in state - 
```navigator.clipboard.write(textFromComponentState).then(function() {
    /* success / close menu / clear text in local state */
  }, function() {
    /* handle failure */
  });```
