### ISSUE TITLE
Context menu does not close when clicking outside in a project that sets state in raw DOM click handlers.

### ISSUE THREAD

**Issue by astegmaier** [vkbansal/react-contextmenu#252]
First of all, I wanted to say thank you for building and maintaining such a useful component! It's saved me a ton of time, and I'd love to help address the bug below, although I'm not 100% sure the right approach.

## Version
2.9.2

## Test Case
https://jsfiddle.net/astegmaier/2c6hyqe8/

## Steps to reproduce
1. Build a project where `ContextMenu` is the child of some larger, state-based component.
2. Directly bind to the DOM `mousedown` event of an element outside of the `ContextMenu`. (In my real-world scenario, this was happening due to a third party library, [handsontable](https://github.com/handsontable/react-handsontable), that was part of my app).
3. Within the click handler, call `setState` on the parent component of `ContextMenu`. (In my real-world scenario, I was trying to hook into handsontable's events and bubble up state changes to my parent component).
4. Open the context menu by right-clicking on the trigger.
5. Click on the DOM element to which the `mousedown` event is bound.

## Expected Behavior
ContextMenu closes

## Actual Behavior
ContextMenu remains open. It takes a second click elsewhere to close it.

**Comment by astegmaier** [comment]
I think the root cause of the issue is in the `ComponentDidUpdate` method of `ContextMenu`. It looks like updates to transition from `hidden => visible` are actually triggered on a timeout ([lines 59-73](https://github.com/vkbansal/react-contextmenu/blob/master/src/ContextMenu.js#L59-L73)), whereas updates to transition from `visible => hidden` ([lines 75-77](https://github.com/vkbansal/react-contextmenu/blob/master/src/ContextMenu.js#L75-L77)) happen immediately.

In the case above, there are two renders:
1. the first one, triggered by the `setState` call in step #3 - in this case, isVisible is true because `ContextMenu` hasn't yet had a chance to learn about the outside click. This call queues up a callback that will (eventually) make the component visible
2. In the second one, ContextMenu finally learns about the outside click, and sets its own state to isVisible = false. So the code within `ComponentDidUpdate` hides the menu.
(but then the callback that was queued up in the first render fires, and the menu is shown again)

I was thinking that it might be possible to fix the bug if we made the code that transitions from `visible => hidden` _also_ behind a timeout. Do you think that might be a viable approach? (I'm new to the library so I'm not sure if that might break something else).

**Comment by wendymungovan** [comment]
I'm also having this issue.  Is there a workaround?

**Comment by vkbansal** [comment]
@astegmaier Sorry for the late reply!.



> I was thinking that it might be possible to fix the bug if we made the code that transitions from `visible => hidden` _also_ behind a timeout.

I believe that this solution will work. Please feel free to open a PR with the suggested change.

**Comment by astegmaier** [comment]
I think I worked around this by modifying the click handler to the parent component to call `setState` after a timeout. This cause `ContextMenu` to handle the outside click (and hide itself) _before_ it has to handle the state change caused by the parent component, so when it handles the second state change, it already knows that it should be hidden.

So where the parent component's click handler  used to say:
`this.setState({ someProperty: 'someValue'});`

It should now would say:
`setTimeout(() => this.setState({ activeCell: e.newActiveCell }));`

It's kind of hacky, but it worked. I still would prefer to have a fix within this library, because I would be easy to hit this bug without realizing it, and I bet there are situations where this workaround wouldn't be sufficient.

**Comment by astegmaier** [comment]
@vkbansal - thanks for taking a look! I'll take a look at making a PR this weekend.

**Comment by romadenysyuk** [comment]
@astegmaier, @vkbansal.

> I was thinking that it might be possible to fix the bug if we made the code that transitions from visible => hidden also behind a timeout.

The other solution could be just recheck the menu visibility inside the deferred wrapper:
```
wrapper(() => {
       if (!this.menu || !this.state.isVisible) return;
       this.menu.style.top = `${top}px`;
       this.menu.style.left = `${left}px`;
       this.menu.style.opacity = 1;
       this.menu.style.pointerEvents = 'auto';
});
```

**Comment by Vadym-Kyrylenko** [comment]
I understand that the problem has not yet been resolved?
![2020_04_30_12_55_40_490](https://user-images.githubusercontent.com/34131434/80698004-7fd30800-8ae2-11ea-928d-368d599245af.gif)
