### ISSUE TITLE
The contextmenu pop up automatically when the left mouse  button was  clicked last more than 2 seconds

### ISSUE THREAD

**Issue by wavemelody** [vkbansal/react-contextmenu#254]
## Version
2.10.0

when the left mouse button is pressed for about 2 seconds, the contextmenu will pop up automatically, wheather the configuration is supported to cancel this feature?

**Comment by wavemelody** [comment]
modify the issue title

**Comment by vkbansal** [comment]
This is expected side-effect for handling touch-inputs.

Please see `holdToDisplay` prop in [API docs](https://github.com/vkbansal/react-contextmenu/blob/master/docs/api.md#contextmenutrigger-)

**Comment by mgummelt** [comment]
Except the docs say that `holdToDisplay` is only relevant for touch screens, which is incorrect.
