### ISSUE TITLE
Cant use ContextMenuTrigger in rows of React Virtualized Table

### ISSUE THREAD

**Issue by amithrajklm** [vkbansal/react-contextmenu#255]
[https://bvaughn.github.io/react-virtualized/#/components/Table](url)
any way to show Context menu without using the trigger?

**Comment by vkbansal** [comment]
https://vkbansal.github.io/react-contextmenu/#/customization

https://github.com/vkbansal/react-contextmenu/blob/master/examples/Customization.js

**Comment by amithrajklm** [comment]
`    render() {
        let data = [{a:1,b:1},{a:2,b:2},{a:3,b:3}]
        return (
            <div>
                <ContextMenuTrigger id="some_unique_identifier" renderTag='Grid.Column' >
                    <Table data={data} onRowRightClick={this.handleRowRightClick} onRowDoubleClick={this.handleRowDoubleClick} >
                        <Column
             
                            label="A"
                            dataKey="a"
                            flexGrow={1}
                            flexShrink={0}
                            width={40}
                        />
                        <Column
                            label="B"
                            dataKey="b"
                            flexGrow={1}
                            flexShrink={0}
                            width={40}
                        />
                      
                    </Table>
                </ContextMenuTrigger>
                <ContextMenu id="some_unique_identifier">
                    <MenuItem data={{ type: 'edit' }} onClick={this.handleClick}>
                        Edit
                    </MenuItem>
                    <MenuItem data={{ type: 'close' }} onClick={this.handleClick}>
                        Close 
                    </MenuItem>
                </ContextMenu>
            </div>
        );
    }
}`

**Comment by timothyjellison** [comment]
@amithrajklm Have you tried using the Column's cellRenderer prop? Something like `cellRenderer={cellData => <ContextMenuTrigger id="some_unique_identifier" >{cellData}</ContextMenuTrigger>}` might do the trick.
