### ISSUE TITLE
Submenu within a submenu interaction with overflow: hidden

### ISSUE THREAD

**Issue by ryanchau** [vkbansal/react-contextmenu#258]
Hi, I have a submenu filled with menuitems that are submenus. In the overarching submenu, sometimes the menuitems get to be a lot, so I've applied overflow-y: auto. This results in strange behavior where the second submenu renders in the original submenu div, and you need to scroll horizontally to reach it. Is there a recommended way of getting the second submenu to appear organically, like it would without overflow-y: auto? 

Thank you!

**Comment by vkbansal** [comment]
Can you attach some images for reference?

**Comment by ryanchau** [comment]
Sorry! here's a jsfiddle to see what I mean:

[https://jsfiddle.net/3sbh0zw8/](https://jsfiddle.net/3sbh0zw8/)

**Comment by vkbansal** [comment]
Probably [this](https://css-tricks.com/popping-hidden-overflow/) might help you
