### ISSUE TITLE
Right click not show contextmenu if another contextmenu opened

### ISSUE THREAD

**Issue by eromoe** [vkbansal/react-contextmenu#26]
As this example:
https://vkbansal.github.io/react-contextmenu/#/multiple-targets?_k=bq0lx9

Current:
1. right click banana , open banana  contextmenu 
2. right click apple, close banana contextmenu 
3. right click apple, open apple contextmenu 

It is better:
1. right click banana , open banana  contextmenu 
2. right click apple, close banana contextmenu and open apple contextmenu

**Comment by smancang** [comment]
yeah, I have the same question,I think it is better to open context menu when another is open. I've read the source code, I think the fixed Modal is not necessary.

**Comment by vkbansal** [comment]
The fixed modal is required to detect outside click.

**Comment by smancang** [comment]
Even you want to detect outside click, you don't need to add a modal. You can add event listener to the document.I think the structure of the library is not reasonable.The ContextMenuLayer method should be in the outmost component.The MenuItem component shoud be in the layer.Then when you right click on one target, it can detect all menu items and decide which one to hide and which one to show.

**Comment by vkbansal** [comment]
I've played around with `document` level eventListeners, but I don't like the idea of having global event listeners and iterating from the event target upto the document and check whether the target is inside or not.

**Comment by smancang** [comment]
The only goal is to implement that when one context menu is open and you right click on another one,it should close the previous one and open the current one. I have an idea, you can add a mousedown event listener to the modal,in the event function, you set the the modal's display style to 'none'.Then you need add a mouseup event listener to every ContextMenuLayer. As a result, when you right click another ContextMenuLayer, the modal's mousedown event and the current ContextMenuLayer's mouseup event will be triggered one after another.The follows is my testing:
﻿<style>
  #bg{
    position:absolute;
    display:block;
    left:0;
    right:0;
    background-color:transparent;
    text-align:center;
    top:0;
    bottom:0;
    line-height: 100%;
  }
  .test{
    width:100px;
    height:100px;
    background-color:red;
    float:left;
  }
  .test:hover{
    background-color:blue;
  }
</style>
<div
  id='bg' onmousedown='mousedown()'>
  I'm a fixed modal.
</div>
<div class='test' onmouseup='mouseup()'>I'm another context menu layer</div>
<script>
  function mousedown(){
    var ele = document.querySelector('#bg');
    ele.style.display='none';
    consoel.log('hide mask');
  }

  function mouseup(){
    console.log('mouseup triggered');
  }
</script>

**Comment by alolis** [comment]
I was just about to post this issue as well and noticed that one already exists :)

It would definitely be nice to see this fixed.

**Comment by vkbansal** [comment]
I've released `v2.0.0-alpha.1` with this feature. Do check it out. Any feedback is welcome 😃
