### ISSUE TITLE
showMenu position Y has unknown calc

### ISSUE THREAD

**Issue by ronaiza-cardoso** [vkbansal/react-contextmenu#266]
## Version
`react-contextmenu@2.11.0`

## Test Case
https://codesandbox.io/s/koq7nypjlo?fontsize=14

## Steps to reproduce
```
handleContextClik = event => {
    console.log("==== event ====", event);
    event.preventDefault();
    const ele = document.getElementById("well");
    const positionInfo = ele.getBoundingClientRect();
    const y = positionInfo.top + positionInfo.height;
    const x = positionInfo.right - positionInfo.left + 145;
    console.log("===== y ====", y);
    console.log("===== x ====", x);
    showMenu({
      position: { x, y },
      target: {},
      id: MENU_TYPE
    });
  };
```

## Expected Behavior
the `y` value reproduce the value that is sent to `showMenu` function

## Actual Behavior
some unknow calc is made with the `y` value

**Comment by vkbansal** [comment]
Why are you writing your custom logic for calculating the position of menu?

You must just pass the position of click event.
