### ISSUE TITLE
SubMenu title type

### ISSUE THREAD

**Issue by Chagui-** [vkbansal/react-contextmenu#269]
## Version
2.11.0

## Test Case
Examples have submenu title accepting a string, but the type is declared as ReactElement<any>, so it gives an error and doesn't compile.

## Steps to reproduce
Examples use title as this:
`<SubMenu title="this is not working">
`
## Expected Behavior
`<SubMenu title="this should work">`

## Actual Behavior
`<SubMenu title={<a>this is how its working right now</a>}>`

**Comment by vkbansal** [comment]
Is this an issue with TS definitions?

**Comment by Chagui-** [comment]
Yes, this is for typescript.
