### ISSUE TITLE
While Dragging Component it ContextMenu got Triggered itself

### ISSUE THREAD

**Issue by Osama081** [vkbansal/react-contextmenu#274]
## Version
1.9.1
i am using react-dnd for managing drag and drop in my project and i am using context menu also but when dragging starts  context menu got triggered dont know why ... 
here what happening.
![gg](https://user-images.githubusercontent.com/30257978/57682884-172e1980-764c-11e9-8b17-67395da076fe.gif)

**Comment by vkbansal** [comment]
have your tried `holdToDisplay` value as `-1`?

**Comment by Osama081** [comment]
Thanks It worked
