### ISSUE TITLE
Only appears on second right click

### ISSUE THREAD

**Issue by FruitAndAShape** [vkbansal/react-contextmenu#276]
My menu only appears the second time I right click on the an item. Why might this be?

I can console log the menu when it's returned from the function that creates it but the first time round it doesn't appear.

**Comment by vkbansal** [comment]
Please share a reproducible code example

**Comment by FruitAndAShape** [comment]
I was returning null from the factory function when there were zero options.

**Comment by Hybueno09** [comment]
@FruitAndAShape    How do u solve it ,I have the same problem

**Comment by FruitAndAShape** [comment]
@Hybueno09 It was happening because sometimes there are no items to show and I wanted to hide the menu altogether, so I returned null. Always returning the menu stops this behaviour, although now it's sometimes showing an empty menu.
