### ISSUE TITLE
Feature Request: Support a variable set of MenuItems

### ISSUE THREAD

**Issue by mgummelt** [vkbansal/react-contextmenu#279]
I need to display different MenuItems depending on what element is right-clicked on.  These items are determined programmatically, so I can't solve this by having multiple different ContextMenus.  If the onShow handler in ContextMenu were to accept data passed in from collect, perhaps that would allow me to re-construct the MenuItems list based on that data.

Thanks!

**Comment by rSensation** [comment]
You can achieve that using connectMenu.

**Comment by dharkness** [comment]
@rSensation Can you even use `<ContextMenu>` without `connectMenu()`?

@mgummelt I'm doing this in combination with a `<ReactTable>`. The main component places the table inside the `<ContextMenuTrigger>` and uses a reference to track the row that was clicked and pass it to the menu.
```
const TableAndMenu = () => {
    const rowRef = useRef();
    const getTrProps = useCallback((state, { original }) => {
        const onClick = e => {
            if (e.button !== 2) {
                // ... normal row click ...
                e.preventDefault();
                e.stopPropagation();
            }
        };
        const onContextMenu = e => {
            rowRef.current = original;
        };
        return {
            onClick,
            onAuxClick: onClick, // middle-click, triggered on context menu click too
            onContextMenu,
        };
    }, [ rowRef ]);
    return (
        <>
            <ContextMenuTrigger id={'command-menu'}>
                <ReactTable
                    ...
                    getTrProps={getTrProps}
                />
            </ContextMenuTrigger>
            <CommandMenu rowRef={rowRef}/>
        </>
    );
};
```
The `<CommandMenu>` component then builds the menu items based on the current value of the reference passed to it.
```
const CommandMenu = connectMenu('command-menu')(({ rowRef }) => {
    const row = rowRef.current;
    const onClick = useCallback((e, data) => {
        // ... perform your action ...
        // clear ref so the menu gets emptied
        rowRef.current = null;
    }, [ rowRef ]);
    return (
        <ContextMenu id={'command-menu'}>
            {row
                ? <>
                    ... menu items using row ...
                </>
                : <></>
            }
        </ContextMenu>
    );
});

export default CommandMenu;
```

**Comment by rSensation** [comment]
@dharkness yes, you can.

connectMenu was added specifically to pass props from a trigger to the menu, as far as I know. So to avoid passing and resetting refs, as in your example, you can just use 'collect' prop for ContextMenuTrigger to choose which props should be passed, and 'trigger' prop for ContextMenu to access those props.

**Comment by dharkness** [comment]
@rSensation I thought `connectMenu()` was needed to connect the trigger to the menu since they are sibling components. I'll have to try it without as I feel my context menu code is overly complicated.

**Comment by mgummelt** [comment]
It'd be nice if `connectMenu` were documented.
