### ISSUE TITLE
Dodgy examples?

### ISSUE THREAD

**Issue by alexmcmillan** [vkbansal/react-contextmenu#28]
react-contextmenu version 1.6.2
react version 15.2.0

I could be wrong, but the examples in your readme appear.... invalid?

Rendering your example:

``` javascript
//The context-menu to be triggered
const MyContextMenu = React.createClass({
    render() {
        <ContextMenu identifier="some_unique_identifier" currentItem={this.currentItem}>
            <MenuItem data={"some_data"} onClick={this.handleClick}>
                ContextMenu Item 1
            </MenuItem>
            <MenuItem data={"some_data"} onClick={this.handleClick}>
                ContextMenu Item 2
            </MenuItem>
            <MenuItem divider />
            <MenuItem data={"some_data"} onClick={this.handleClick}>
                ContextMenu Item 3
            </MenuItem>
        </ContextMenu>
    },
    handleClick(e, data) {
        console.log(data);
    }
});
```

Generates the console error message (for me):

>Uncaught Invariant Violation: ContextMenu.render(): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.

Perhaps this JSX should be wrapped in a `return (...)` ?

Also, according to [this line](https://github.com/vkbansal/react-contextmenu/blob/master/src/menu-item.js#L12), the `MenuItem` prop `data` is expected to be an `object`, but your example passes strings.

**Comment by vkbansal** [comment]
Have a look a examples folder

**Comment by alexmcmillan** [comment]
I wasn't asking for help - I was just letting you know your documentation appears wrong.

**Comment by vkbansal** [comment]
OK, Then can you open a PR with the Fix?

**Comment by vkbansal** [comment]
Ignore. I'll fix it myself

**Comment by alexmcmillan** [comment]
Yeah I actually forked and started fixing it but thought you'd have a better idea of example objects to pass as `data` etc.

Just FYI: your commit missed the first render in your example.

Glad I could help!
