### ISSUE TITLE
MenuItem Click not get fired.

### ISSUE THREAD

**Issue by patilrevansidh** [vkbansal/react-contextmenu#281]
Click event does not fire.
I'm using this library, I have touch screen laptop. 
`onClick` event not get trigger when click using mouse. But using touch screen it gets triggered. Can you suggest any workaround
Hardware: Touchscreen

**Comment by DaleSalcedo** [comment]
I'm having the same issue except i cannot trigger the onClick on PC or anything at all

```
return (
      <div>
        <ContextMenuTrigger
          id={"WTFasdfasdf"}
        >
        <div className="playlist-header">
          <div className="playlist-row">
           ......
          </div>
        </div>
        </ContextMenuTrigger>
        <ContextMenu
          id={"WTFasdfasdf"}
        >
          <MenuItem onClick={() => alert("why won't you work")}>Test</MenuItem>
        </ContextMenu>
      </div>
    );
```

**Comment by conmute** [comment]
Having same issues after couple of re-renders (on init works well though…)

**Comment by vkbansal** [comment]
Which version are you using? If you are using `2.11.0`, please try `2.10.0`

**Comment by KirillSuhodolov** [comment]
at 2.10.0 click does not fire too

**Comment by perry-mitchell** [comment]
2.10.0 also doesn't work for me. Using Ubuntu on a PC, latest chrome.

**Comment by vkbansal** [comment]
I unable to reproduce the issue
https://codesandbox.io/s/spring-feather-xdsbr

If you can provide an example that would be helpful

**Comment by heinz-leung** [comment]
After I given a **unique** id for **each** ContextMenu and ContextMenuTrigger, the problem solved.
I think this issue is caused by multiple ContextMenu with the same ID appear in the same page.

**Comment by jblazevicClover** [comment]
> I am using `2.11.0`
> After I given a **unique** id for **each** ContextMenu and ContextMenuTrigger pairs, the problem solved.
> I think this issue is caused by multiple ContextMenu with the same ID appear in the same page.

niceee. Thanks maan! :)

**Comment by hungdev** [comment]
in my case, set css for MenuItem `height: 100%;`

```
      <ContextMenu id="context_menu" className='menu-context'>
        <MenuItem className='context-menu-item' data={{ foo: 'bar' }} onClick={handleDeleteContext}>
          <Translate contentKey="entity.action.delete" />
        </MenuItem>
```

```
.context-menu-item {
  width: 150px;
  height: 100%;
}
```

**Comment by hungdev** [comment]
@heinz-leung thanks bro :)
