### ISSUE TITLE
TypeError: can't convert undefined to object - connectMenu.js:81. Only in production env

### ISSUE THREAD

**Issue by meetajhu** [vkbansal/react-contextmenu#284]
## Version
v2.11.0

## Test Case
```
import React from "react";
import ReactDOM from "react-dom";
import { ContextMenu, MenuItem, ContextMenuTrigger } from "react-contextmenu";

function handleClick(e, data) {
  console.log(data.foo);
}

function MyApp() {
  return (
    <div>

      <ContextMenuTrigger id="some_unique_identifier">
        <div className="well">Right click to see the menu</div>
      </ContextMenuTrigger>

      <ContextMenu id="some_unique_identifier">
        <MenuItem data={{foo: 'bar'}} onClick={this.handleClick}>
          ContextMenu Item 1
        </MenuItem>
        <MenuItem data={{foo: 'bar'}} onClick={this.handleClick}>
          ContextMenu Item 2
        </MenuItem>
        <MenuItem divider />
        <MenuItem data={{foo: 'bar'}} onClick={this.handleClick}>
          ContextMenu Item 3
        </MenuItem>
      </ContextMenu>

    </div>
  );
}

ReactDOM.render(<MyApp myProp={12}/>, document.getElementById("main"));
```

## Steps to reproduce
Take Webpack build with `NODENV=Production` and run the react app. Browser console shows error in `connectMenu.js:81 TypeError: can't convert undefined to object` . Development environment works fine.

## Expected Behavior

Not sure if Babel related error. But app should run in Production build.

## Actual Behavior

Everything is fine on development environment. However, when I compile my packs to production-ready environment (NODE_ENV=production), react-contextmenu gives an error on startup in file `connectMenu.js:81`

**Comment by meetajhu** [comment]
Fixed issue by excluding node_modules From Being Transpiled By Babel-Loader. If your using Webpacker for Rails add this line 
`environment.loaders.delete('nodeModules')`
to
`config/webpack/environment.js`
which should look like
```
const { environment } = require('@rails/webpacker')
environment.loaders.delete('nodeModules')
module.exports = environment
```

**Comment by eyelly-wu** [comment]
@meetajhu How to solve the problem without using Webpacker for Rails

**Comment by meetajhu** [comment]
> @meetajhu How to solve the problem without using Webpacker for Rails

in your webpack.config.js add "exclude: /(node_modules)/" under your babel-loader settings

`
//webpack.config.js

module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        exclude: /(node_modules)/,
        loader: 'babel-loader'
      }
]
}
`

**Comment by eyelly-wu** [comment]
@meetajhu I found some other solutions

**1. change the react-contextmenu's package.json**
from
![image](https://user-images.githubusercontent.com/24505069/61511586-c959d700-aa29-11e9-871f-e72ba0a6adb6.png)
to
![image](https://user-images.githubusercontent.com/24505069/61511300-d2967400-aa28-11e9-802e-22deac49aabd.png)

**2.  delete "module": "es6/index.js" of the react-contextmenu's package.json** 

**3. change wepack.config.js like this**
```js

resolve: {
  mainFields: ['main', 'module']
}
```

**Comment by barbalex** [comment]
These "solutions" are not easy to implement in every situation. I tried both and they did not work for me. I had to revert to copying the `react-contextmenu.js`-file created in the dist folder after building into my project. Very hacky.

And my case will not be rare: It seems that this problem occurs when this lib is used in gatsby (my case). Which is quite popular.

So I feel that this issue should be re-opened.

**Comment by barbalex** [comment]
@eyelly-wu I have to admit I do not completely understand your solution. Do you think this could be converted into a pull request? Hoping it would be accepted?

**Comment by jazevedo620** [comment]
Why is this issue closed? The same bug appears for me in Gatsby

**Comment by stevenkkim** [comment]
This bug is also appearing for me in Gatsby.
