### ISSUE TITLE
Ability to avoid some subscriptions to document events.

### ISSUE THREAD

**Issue by rSensation** [vkbansal/react-contextmenu#286]
Is it possible to opt out of some subscriptions in registerHandlers method of ContextMenu. It would be great to have more control over it with props, just to add flexibility in some tricky use cases.

**Comment by vkbansal** [comment]
Can you provide some examples?

**Comment by rSensation** [comment]
For example, I had an issue with "contextmenu" subscription. For some reason, the menu was not opening in my app on Android because long touch would lead to "contextmenu" event (I assume it was being fired by 3rd party grid component I was using), which by default hides menu. I ended up fixing it with a hack, but it would be nice to have flexibility in such cases.

**Comment by vkbansal** [comment]
Can you open a PR with your proposed fix?
