### ISSUE TITLE
Prevent SubMenu from closing on mouse leave

### ISSUE THREAD

**Issue by AdenFlorian** [vkbansal/react-contextmenu#288]
It's too easy IMO to accidentally close a sub menu by accidentally moving your mouse off of it. I use the `hideOnLeave` prop on the `ContextMenu`, and that works great, but it only affects the base menu, and not any sub menus.
Assuming that is working as intended, I propose adding the same prop to the `SubMenu` component, and have it function in the same way.

Thanks for considering!

## Version
2.11.0

**Comment by vkbansal** [comment]
So you want to have `hideOnLeave` option on `<Submenu />`?

**Comment by AdenFlorian** [comment]
Yes please! I can take a shot at a PR if you want.

**Comment by vkbansal** [comment]
A PR is always welcome

**Comment by Galkon** [comment]
@AdenFlorian this was one of my biggest frustrations - but with the entire menu. I've just created a PR for a new prop for `ContextMenu` called `hideOnLeaveDelay`, you can check it out here: https://github.com/vkbansal/react-contextmenu/pull/295
