### ISSUE TITLE
In MenuItem, don't override className prop, but extend it

### ISSUE THREAD

**Issue by wuppious** [vkbansal/react-contextmenu#293]
Currently, you can give `MenuItem` classNames through the `attributes` prop. These are then applied to the element, but also overriding any className given as a direct prop. https://github.com/vkbansal/react-contextmenu/blob/22d299e986367e81bcde575b4abeffdb9ace0a5c/src/MenuItem.js#L56-L65

The reason why this might be problematic, is that some css-in-js libraries such as `styled-components` apply an automatically generated className to the props, which then gets overridden in the render method.

My suggestion would be to accept this className prop and extend it instead of overriding.

**Comment by wuppious** [comment]
Meanwhile, a workaround is to wrap the `MenuItem` into a functional component and apply the generated className to the attributes.

```javascript
const MenuItemWithClassName = props => (
  <MenuItem {...props} attributes={{ className: props.className }} />
);
```

**Comment by vkbansal** [comment]
Good catch!. This library was written when CSS-in-JS libraries were not a thing.

Now that they are a thing, it should be taken care of. Will you be willing to submit a PR?

**Comment by wuppious** [comment]
I can have a look during the weekend.

**Comment by wuppious** [comment]
@vkbansal PR is done, however it fails due to Code Climate config error. I don't believe I can affect that, so please check into it.

**Comment by vkbansal** [comment]
No issues. I'll take care of it
