### ISSUE TITLE
ContextMenu onShow() / onHide() callbacks

### ISSUE THREAD

**Issue by alolis** [vkbansal/react-contextmenu#30]
Hello,

I am wondering if it's possible to have an `onShow` and an `onHide` callbacks passed to `ContextMenu` as props in a future release.

For example, in my case, I would like to be able to change the css class of the target which the ContextMenu showed and change it back after hiding it.

**Comment by alolis** [comment]
Well, it seems that the following will do the trick for `onShow` alternative:

```
window.addEventListener('contextmenu', this.handleContextMenuEvent);
```

If there is a better way I am all ears.

**Comment by vkbansal** [comment]
This is good idea. I keep this in mind for next release

**Comment by vkbansal** [comment]
I've released `v2.0.0-alpha.1` with this feature. Do check it out. Any feedback is welcome 😃

**Comment by alolis** [comment]
@vkbansal , is my code supposed to work if i update to 2.x ?

**Comment by vkbansal** [comment]
Not out of the box but check the changes:
https://github.com/vkbansal/react-contextmenu/releases/tag/v2.0.0-alpha.1

And updated Readme:
https://github.com/vkbansal/react-contextmenu/blob/v2/README.md

**Comment by alolis** [comment]
@vkbansal , reading now. The example i linked though still uses `ContextMenuLayer` so it probably needs fixing.

**Comment by vkbansal** [comment]
> The example i linked though still uses `ContextMenuLayer`

Fixed it. I was too lazy to update the component name. It should not be confusing now.

**Comment by alolis** [comment]
@vkbansal , cool. I also used `onShow` and it seems to be working normally. I haven't found any problems at the moment so you can probably close this issue.

**Comment by vkbansal** [comment]
Cool
