### ISSUE TITLE
Wrong prop type for renderTag property of ContextMenuTrigger

### ISSUE THREAD

**Issue by glebpl** [vkbansal/react-contextmenu#300]
renderTag of ContextMenuTrigger now has type 
```
PropTypes.oneOfType([
    PropTypes.node,
    PropTypes.func
])
```
But it should have type PropTypes.elementType which allows native html tags and any custom components.

## Version
2.13.0

## Steps to reproduce
1. Create custom function component MyComponent.
2. Pass it as renderTag to ContextMenuTrigger

## Expected Behavior
Check of prop types should pass

## Actual Behavior
Check of prop types fails (Failed prop type: Invalid prop `renderTag` supplied to `ContextMenuTrigger`)

**Comment by vkbansal** [comment]
Will you open a PR with the fix?

**Comment by glebpl** [comment]
I can, but never did it before)) Should I become a contributor to create a new branch and than a PR?

**Comment by vkbansal** [comment]
You can follow the intruction mention in the post
https://codeburst.io/a-step-by-step-guide-to-making-your-first-github-contribution-5302260a2940

**Comment by glebpl** [comment]
Thank you for the article. I suppose to make a PR tomorrow
