### ISSUE TITLE
Disabling right clicks

### ISSUE THREAD

**Issue by ads692** [vkbansal/react-contextmenu#305]
Hi I just started using this context menu and fits my work case. Thank you!

Just checking if there's a way to KEEP the long left clicks and DISABLE the right clicks instead? I want the right click to still trigger the operating system's context menu by default.

**Comment by coderliush** [comment]
@ads692  ContextMenuTrigger has a prop 'disable'，i think you can set it to false by default and set it to true in the right clicks。It works for me，you can try it

**Comment by ads692** [comment]
Thanks @coderliush . I was able to map the 'disable' prop to a boolean value and utilize it to enable/disable my right click functionality. Works like a charm :)
