### ISSUE TITLE
Menu doesn’t dismiss on click when it contains a submenu

### ISSUE THREAD

**Issue by ivailop7** [vkbansal/react-contextmenu#308]
Great plugin! Keep up the great work. I’ve noticed a small bug. That looks very similar to https://github.com/vkbansal/react-contextmenu/issues/297 but it pertains to a menu having a submenu.

## Version
2.13

## Test Case
Don’t have one sorry.

## Steps to reproduce
Have a menu containing an item and a submenu with items.

## Expected Behavior
Dismiss the menu with the displayed submenu upon clicking away from it on the page.

## Actual Behavior
Clicking away from the displayed menu doesn’t dismiss it. It’s only upon hovering over the already displayed submenu that it makes it disappears, after clicking somewhere else on the page.

**Comment by ivailop7** [comment]
The issue is not present in 2.10, only in 2.13

**Comment by vkbansal** [comment]
Thanks for reporting. I'll take a look at this when I have time.

Meanwhile if you are able to find the fix, feel free to open a PR with the fix.
