### ISSUE TITLE
Option to detect context menu coordinates

### ISSUE THREAD

**Issue by ads692** [vkbansal/react-contextmenu#311]
Hi, I wanted to check if there's a way to detect the context menu's cooridinate values for left and top based on the container it is placed in? Right now it seems to be calculating it only from the top layer window's values.

**Comment by vkbansal** [comment]
You can do this:
```
const menu = document.querySelector('.react-contextmenu')
menu.getBoundingClientRect()
```

You can also pass a custom class and use that instead
