### ISSUE TITLE
it can be used with the Table component ?

### ISSUE THREAD

**Issue by dayongi** [vkbansal/react-contextmenu#315]
I would like to know if it can be used with the Table component, I have this requirement now
like this example：
![image](https://user-images.githubusercontent.com/41787764/74354879-f5d6a580-4df6-11ea-9900-32e512ffc3e2.png)

**Comment by vkbansal** [comment]
Yes . it can be.  https://github.com/adazzle/react-data-grid/ uses this

You can also take a look at `renderTag` prop
https://github.com/vkbansal/react-contextmenu/blob/master/docs/api.md#contextmenutrigger-
