### ISSUE TITLE
Support for opening context menu using keyboard contextmenu and Shift+F10 button

### ISSUE THREAD

**Issue by nowrinmohamed** [vkbansal/react-contextmenu#319]
****
only right click opens context menu. There is no support for keyboard accessibility like shift+F10 or context menu button in keyboard. using handleContextClick() doesnt work as expected. 

**## Version**
 2.13

## Steps to reproduce

- Add handleContextClick() whenever oncontextmenu is triggered (in my case contextmenu button in keyboard)

- use keyboard context menu button to open context menu

## Expected Behavior

When context menu is not open, menu must open. If already its open, then no action.

## Actual Behavior

It tries to work as rightclick and not as keyboard context menu. it saves the mouse pointer location and then hides and opens context menu. But this is not the expected behaviour.

**Comment by vkbansal** [comment]
Hi @nowrinmohamed you are welcome to open a PR with the enhancement.
