### ISSUE TITLE
Hide context menu when window is resized

### ISSUE THREAD

**Issue by fronteed** [vkbansal/react-contextmenu#32]
## Version

1.2.0
## Steps to reproduce

Open context menu via right click, change window's size - context menu still visible, in the wrong place.
## Expected Behavior

Context menu should be hidden on window resize event.
## Actual Behavior

Appears visible in the wrong place.

**Comment by vkbansal** [comment]
For now, you can handle this custom logic using `monitor.hideMenu()`

**Comment by fronteed** [comment]
@vkbansal this should be handled without extra code

**Comment by vkbansal** [comment]
I've released `v2.0.0-alpha.1` with this feature. Do check it out. Any feedback is welcome 😃
