### ISSUE TITLE
Prevent menu to show up after fire dragStart. 

### ISSUE THREAD

**Issue by robert8888** [vkbansal/react-contextmenu#321]
## Actual Behavior

When dragStart is fired menu shows up after value setted to holdToDisplay. Yes you can set holdToDisplay on -1 but still is not desire behavior. 

Best

**Comment by vkbansal** [comment]
This is intended behaviour. Changing this will make it stop working on touch screen devices.

**Comment by robert8888** [comment]
Ok. I get this point of view, but still i suppose that you can catch drag start / drag end on the root (eg. body) element  (it is bubbling in most case) and then don't show menu during dragging.

Best.

**Comment by vkbansal** [comment]
I'm not too familiar with how things work on touch devices. Can you share a code sample of what you are proposing? Even better if you code provide a PR.

**Comment by vkbansal** [comment]
closing issue see #339
