### ISSUE TITLE
Possible reason for no background color display in Electron?

### ISSUE THREAD

**Issue by yifax** [vkbansal/react-contextmenu#324]
## Version
1.9.1

## Test Case
I just tried the example demo code, using it in an electron project. Maybe this is the problem?

## Steps to reproduce
![2020-04-20 165800](https://user-images.githubusercontent.com/14918900/79810614-4bb05800-8328-11ea-8c60-5983ef111292.png)

## Expected Behavior
Menu Style displays correctly.

## Actual Behavior
No background, border, just text.

**Comment by vkbansal** [comment]
This library does not apply any styling expect for display and positioning. You need to style it yourself.

https://github.com/vkbansal/react-contextmenu/blob/master/docs/usage.md#styling
