### ISSUE TITLE
Menu Appear behind scrollbar

### ISSUE THREAD

**Issue by soubhikchatterjee** [vkbansal/react-contextmenu#328]
When i use the context menu on a div that has overflow: scroll, the menu appears behind the scrollbar. Is there anyway to appear over the scrollbar?

![image](https://user-images.githubusercontent.com/863672/82005889-34912b80-9684-11ea-9825-95528c474a01.png)

## Version
2.13.0

 

## Steps to reproduce
Create a div
specify a widh and height
add some content to that the div shows scrolling
try to right click near the scroll area
menu appears behind scrollbar

## Expected Behavior
Menu should appear over scrollbar

## Actual Behavior
menu appears behind scrollbar

**Comment by soubhikchatterjee** [comment]
@vkbansal Please can you help me with the above query?

**Comment by vkbansal** [comment]
@soubhikchatterjee This issue appears to be a CSS issue and not to do anything with the library itself.

Have you tried playing with the `z-index` of the menu?

**Comment by vkbansal** [comment]
closing issue see #339
