### ISSUE TITLE
Have to click two time to dismiss

### ISSUE THREAD

**Issue by MattNot** [vkbansal/react-contextmenu#331]
## Version
2.13.0
## Test Case
Not have
## Steps to reproduce
I've an Ace editor as Trigger.
When i click with right button it appears, if I click on the editor with left button i've to click 2 times to make the context menu disapear
## Expected Behavior
Disappear in a clik

**Comment by vkbansal** [comment]
This issue appears to be with ace editor itself and not this library. This will happen when some element blocks event bubbling by using `event.stopPropagation()`
