### ISSUE TITLE
SubMenu custom right arrow icon.

### ISSUE THREAD

**Issue by nkemcels** [vkbansal/react-contextmenu#335]
Thanks for creating this amazing library. You guys are awesome.

Please is it possible to change the right arrow that is shown for the `SubMenu` component? 
I'd want to use a `fontawesome` chevron icon.

![CHANGE ICON](https://user-images.githubusercontent.com/40471180/87289918-3432d680-c4f5-11ea-98c0-92748392a533.png)

**Comment by vkbansal** [comment]
You can do it by using your custom css.

**Comment by nkemcels** [comment]
Hi @vkbansal 
Thanks for your response. 
Please is it possible for you to do some sort of an example of how to achieve it? Thanks

**Comment by vkbansal** [comment]
You can refer to https://codepen.io/egf/pen/jzylw

Or you can use stackoverflow or google.

I'm closing this ticket as this is not related the library and is a CSS question.
