### ISSUE TITLE
Not working property when using with react-router

### ISSUE THREAD

**Issue by joonki34** [vkbansal/react-contextmenu#39]
Context menu is popping up at the left corner of the window when I go to the previous page and come back to the page where I right-clicked the view before. Here is the step I followed.

1. Go to the example page (https://vkbansal.github.io/react-contextmenu/#/?_k=u9aaao)
2. Click 'Multiple Targets' tab
3. Right click 'Banana' or another view.
4. Go back
5. Come back to the page

## Version
1.6.3

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

## Steps to reproduce
![output_ttfyom](https://cloud.githubusercontent.com/assets/1715023/20037131/b6624904-a45d-11e6-8d87-6a63fc751dbb.gif)

## Expected Behavior
When coming back to the page, the context menu should not be prompted.

## Actual Behavior
The context menu is appeared at the left corner of the window.

**Comment by vkbansal** [comment]
Thanks for reporting. This has been fixed in v2
