### ISSUE TITLE
Cannot trigger menu and choose item with mousedown/mousemove/mouseup sequence

### ISSUE THREAD

**Issue by philiphubbard** [vkbansal/react-contextmenu#43]
With a native context menu, it is possible to trigger the menu and choose an item from it with one fluid sequence of pressing the mouse, keeping it held down while moving to the desired item, and releasing the mouse over that item.  With react-contextmenu, this behavior is not supported: it is necessary to click once to trigger the menu, then click again to choose an item from that menu.

**Comment by vkbansal** [comment]
Thanks for opening the issue.

To be clear, I'm not trying to replicate the exact behaviour of a native contextmenu.

Moreover, implementing such behaviour will be a nightmare (using JS). Many people use this component on touch-based devices so what you suggest may not work out for them.
