### ISSUE TITLE
Support Right to Left contextmenus

### ISSUE THREAD

**Issue by yotamberk** [vkbansal/react-contextmenu#44]
Is there an easy way to make the contextmenus open rtl? 
For example, when using the SubMenu, it always opens to the right (unless close to the end of the page) and I'd like it to always open to the left unless close to the left side of the end of the page.

**Comment by vkbansal** [comment]
This can be done. I'll have to look into it.

**Comment by yotamberk** [comment]
@vkbansal Thanks!
