### ISSUE TITLE
How to programmatically open context menu?

### ISSUE THREAD

**Issue by bluejamesbond** [vkbansal/react-contextmenu#46]

**Comment by vkbansal** [comment]
Which version are you using?

**Comment by bluejamesbond** [comment]
Latest

**Comment by vkbansal** [comment]
`2.0.0-aplha-x`?

**Comment by bluejamesbond** [comment]
What is the function?

**Comment by vkbansal** [comment]
You can do as follows:

```js
import { showMenu } from 'react-contextmenu/modules/actions'

showMenu({
    position: {x, y},
    target: this.elem,
    id: this.props.id
});
```

> Note: This is not officially supported

**Comment by bluejamesbond** [comment]
Perfect. Thanks!

**Comment by greggman** [comment]
Any reason not to make this officially supported? It seems like it would be really useful to be able to use `oncontextmenu` to make the menus appear.

**Comment by vkbansal** [comment]
It is not officially supported because, much  of the custom logic like passing props to `ContextMenu` is handled automatically.

**Comment by lastlegion** [comment]
The menu shows up but hides as soon as I hover over any option. Any ideas?
