### ISSUE TITLE
why does it show up the context-menu when long time left click?

### ISSUE THREAD

**Issue by smancang** [vkbansal/react-contextmenu#47]
## Version
2.0.0-alpha.2

## Steps to reproduce
press the left mouse button on the element and don't loosen it for 1s.
## Expected Behavior
nothing happened
## Actual Behavior
the context menu shows up

The code is in ContextMenuTrigger.js
`
    return _ret = (_temp = (_this = _possibleConstructorReturn(this, (_ref = ContextMenuTrigger.__proto__ 
......

        _this.mouseDown = true;

        setTimeout(function () {

          if (_this.mouseDown) _this.handleContextClick(event);

        }, _this.props.holdToDisplay);

      }
......
`

I don't know why did you do this, it's so strange and unreadable.
I don't want to show up the context menu because I'm just dragging the element.

**Comment by vkbansal** [comment]
The actual source code is in `src` folder.

**Comment by smancang** [comment]
I've known it.
`javascript


handleMouseDown = (event) => {
        if (this.props.holdToDisplay >= 0 && event.button === 0) {
            event.persist();

            this.mouseDown = true;
            setTimeout(() => {
                if (this.mouseDown) this.handleContextClick(event);
            }, this.props.holdToDisplay);
        }
    }
`
But you have't answer the question yet. It's understandable that you register  'Touch' event to show the context menus in some device such as mobilephone or ipad. But why do you register left mouse click event to show the context menus for long click?

**Comment by vkbansal** [comment]
> But why do you register left mouse click event to show the context menus for long click?

For browser that do not support touch event.

**Comment by smancang** [comment]
I don't think you solve a problem, but create a problem. What should I do when I drag an element and just left click the element for long time? Do you think it is appropriate to show context menu in these situations?

**Comment by whathejoe** [comment]
For anyone curious how to disable the long press trigger just set a negative holdToDisplay value

`<ContextMenuTrigger id={*id*} holdToDisplay={-1}`

Not defining a value for that prop will have it default to 1000

**Comment by vkbansal** [comment]
Thanks a lot @whathejoe !!!

Will definitely at this to README.

**Comment by o0void0o** [comment]
im getting the same issue on 2.14.0 holdToDisplay={-1} did not solve this for me?... Im dragging  a list item and the menu pops up while dragging..
