### ISSUE TITLE
Can we use this with SVG paths ?

### ISSUE THREAD

**Issue by nish1013** [vkbansal/react-contextmenu#51]

**Comment by vkbansal** [comment]
You can use anything that can be used with react.

**Comment by nish1013** [comment]
`<path
          id={link.id}
          key={ind}
          d={d}
          style={lineStyle}
          strokeWidth={2}
          />`

We're unable to provide a target for above as it'll draw on a   <SVGCanvas>.

We need to show the context menu when click on <path> elements

**Comment by nish1013** [comment]
We can get callback when click on a `<path>` using below code ,

```
<path
          id={link.id}
          key={ind}
          d={d}
          style={lineStyle}
          strokeWidth={2}
          onContextMenu={(e)=>{console.log('onContextMenu');e.preventDefault();that.onContextMenuLink(ind,data);}}/>
```

But how do we bring the context menu from that callback ?

**Comment by vkbansal** [comment]
have you tried using `renderTag='path'` prop on the wrapped component?
