### ISSUE TITLE
Disabling `ContextMenuLayer` based on props

### ISSUE THREAD

**Issue by aurels** [vkbansal/react-contextmenu#54]
Hi.

We call the "higher order function" `ContextMenuLayer` like this : 

    export default ContextMenuLayer('albums-list')(Results)

In our app, we would like to have the context menu setup only in certain conditions (let's say according to `this.props.contextMenusEnabled`). Is there another way to call `ContextMenuLayer` in order to have conditions around ? In `render`?

Thanks !

**Comment by vkbansal** [comment]
Hi, as I understand, you are using 1.x version.

I've rolled out 2.0 and what you ask is pretty easy to achieve in that version.

I've no plans to maintain 1.x, so check if you can upgrade? If not let me know. We'll figure out a solution

**Comment by aurels** [comment]
Hi, 

Thanks for your reply.

I figured out a way to do it : one version of the component is wrapped into `ContextMenuLayer` and not the other, and I switch between the two.

In my case I have `Results` and `ResultsWithContextMenuLayer`, the second wrapping the other. And they therefore accept the same props.

Anyway, I'll have to switch to 2.0 in a near future then ;-) I hope most of it stays compatible :-p
Thank you again !

**Comment by vkbansal** [comment]
Glad that you were able to figure it out 😄
