### ISSUE TITLE
 it still shows up the context-menu when long time left click

### ISSUE THREAD

**Issue by smancang** [vkbansal/react-contextmenu#55]
## Version
2.0.0-beta.1

## Steps to reproduce
press the left mouse button on the element and don't loosen it for 1s.

## Expected Behavior
nothing happened
## Actual Behavior
the context menu shows up

It's the same with the closed [#47](https://github.com/vkbansal/react-contextmenu/issues/47).
The problem hasn't been solved yet!

**Comment by whathejoe** [comment]
https://github.com/vkbansal/react-contextmenu/issues/47#issuecomment-265378129

**Comment by smancang** [comment]
I'm sorry, I haven't see the comment.

**Comment by vkbansal** [comment]
I have also added to readme
