### ISSUE TITLE
The IE 11 browser doesn't recognize the syntax a: { c, d }

### ISSUE THREAD

**Issue by smancang** [vkbansal/react-contextmenu#57]
## Version
2.0.0-beta.1

## Steps to reproduce
run an web site in IE 11

## Expected Behavior
normal

## Actual Behavior
occur an error:
in ContextMenuTrigger.js

...
(0, _actions.showMenu)({
        position: { x, y },
...

The IE 11 doesn't recognize the syntax "position: { x, y }"

**Comment by vkbansal** [comment]
Ideally Babel should transpile the code. I'll have a look

**Comment by vkbansal** [comment]
Where are you getting this error? locally or on hosted examples?

**Comment by vkbansal** [comment]
unable to reproduce.
