### ISSUE TITLE
IE11 - Unable to get property 'id' of undefined or null reference

### ISSUE THREAD

**Issue by Warcrea** [vkbansal/react-contextmenu#58]
## Version
2.0.0-beta.2

## Steps to reproduce
Right click on a contextMenuTrigger area in IE11.

## Expected Behavior
Context menu is displayed succesfully as it is in Chrome and Firefox.

## Actual Behavior
Throws error: Unable to get property 'id' of undefined or null reference

Referring to this line: 
_this.handleShow = function (e) {
            if (e.detail.id !== _this.props.id) return;

**Comment by vkbansal** [comment]
You tried to open example site?

**Comment by Warcrea** [comment]
Yep

![contextmenu-idbug](https://cloud.githubusercontent.com/assets/9248826/21187142/dc42a1fe-c20e-11e6-8502-4db20a9e2ea3.png)

**Comment by Warcrea** [comment]
My mistake, the version is 2.0.0-beta.2

**Comment by vkbansal** [comment]
This should be fixed in latest master.

Can you take a pull and check?

I'll publish new version after confirmation

**Comment by Warcrea** [comment]
Confirm this works now, thanks very much!
