### ISSUE TITLE
Long press will trigger the context menu

### ISSUE THREAD

**Issue by xiguaaxigua** [vkbansal/react-contextmenu#60]
Hi man,
Long press will trigger the context menu.

**Comment by vkbansal** [comment]
Please take a look at readme thoroughly before reporting issues

**props.holdToDisplay**

Type: Number (optional)

Default: 1000

This is applicable only for touch screens. The time (in ms) for which, user has to hold down his/her finger before the menu is shown.

> Note: To disable the long press trigger on left-click just set a negative holdToDisplay value such as -1

**Comment by DanHarman** [comment]
It seems to trigger in the latest chrome when moving a scroll bar in a div wrapped by the trigger. Anyway not a big issue, will just disable.
