### ISSUE TITLE
handleOutsideClick bug

### ISSUE THREAD

**Issue by skipjack** [vkbansal/react-contextmenu#61]
## Version
2.0.0-alpha.2

## Test Case
Unfortunately I can't do this now but if it would be helpful I can try to throw an example together soon.

## Steps to reproduce
1. Use a Link within a ContextMenu.
2. Open the ContextMenu and navigate through the Link.
3. Click anywhere in the document and see the error that continues to be thrown.

## Expected Behavior
Component should remove `handleOutsideClick` listener on unmount. 

## Actual Behavior
Error is thrown because `this.menu` is `null` after unmounting:

```js
handleOutsideClick = (e) => {
    if (!this.menu.contains(e.target)) hideMenu();
}
```

![image](https://cloud.githubusercontent.com/assets/8988697/21316586/68121246-c5cf-11e6-9a97-43aaf6fe7a9e.png)

Other than this, the library has been great -- thank you! I'd be happy to open a PR if you point me in the right direction. It does look like you are trying to unregister the the listener in `componentWillUnmount` so I'm not exactly sure what's going on.

**Comment by vkbansal** [comment]
Which Browser and OS are you using?

**Comment by skipjack** [comment]
Mac OS 10.10.5, Chrome 54.0.2840.98

**Comment by vkbansal** [comment]
Thanks, I'll try to debug it. It would be really helpful you can give me some example where this is happening.

**Comment by skipjack** [comment]
@vkbansal great thank you, I'll try to get a something together that demos the problem.

**Comment by skipjack** [comment]
@vkbansal here's a [webpack bin](http://www.webpackbin.com/EJf2V044G) that demos the issue:

![image](https://cloud.githubusercontent.com/assets/8988697/21429041/0c9bf270-c82b-11e6-9e64-bfdd5d734ea5.png)

Steps to reproduce:

1. Navigate to the second page
2. Right click the text that says right click
3. Navigate back to home
4. Click anywhere to see the error

**Comment by vkbansal** [comment]
I got the root cause of the issue! Thanks

> Note to self: remove event listeners even on unmount
