### ISSUE TITLE
Compatibility with CSS-in-JS libs: Don't render context menu when it is not visible

### ISSUE THREAD

**Issue by gravitypersists** [vkbansal/react-contextmenu#62]
[Currently](https://github.com/vkbansal/react-contextmenu/blob/master/src/ContextMenu.js#L44), when the `ContextMenu`'s state swaps out to `isVisible`: false, the class `react-contextmenu--visible` is added to the `<nav>` child rendered by `ContextMenu`.

This means, without css on the page, it is impossible to hide the context menu. It creates a dependency which would be better circumvented if it didn't render that at all. I can create a PR for that change if desired, but I'm not sure this is desired yet.

Why this is frustrating:

We are using [aphrodite](https://github.com/Khan/aphrodite) for all of our styles. This is a pretty strong trend in JS frameworks lately (though it's not the only way), as it allows components to be packaged up with styles without requiring extra css. What aphrodite does is create a `<style>` tag in the head with css rules declared by JS, these rules map back to the element by a generated css class name. Some of our components have no means of adding css to the page other than like this.

So something using this library would also require external css as an added dependency, or be forced to add a css rule to the page, which is less than ideal.

Solutions:

A solution I'm not crazy about for this problem: allow us to define styles for these different states. `<ContextMenu styleWhenNotVisible={{}} ... />`.

Better solution: There really isn't much styling in this library. `MenuItem` has some but children are free to be styled and structured freely. In fact, the only reason I am using `MenuItem`, is to leverage it's auto-closing from `onClick` behavior. Including `opacity: 0` is really less of a css concern and more of a JS concern (whether or not to show, as opposed to how to show, as reflected by the name of the state variable, `isVisible`), and as such, should just be managed by the JS by determining whether to render or not render.

Agree?

**Comment by vkbansal** [comment]
I've have not use any CSS-in-JS libs yet. So, I will have to think through it.

**Comment by gravitypersists** [comment]
Here's a great comparison of the different techniques, but there's also some links down below with some motivations behind doing it.

https://github.com/MicheleBertoli/css-in-js

The biggest thing is that you don't create build dependencies on users using your library. That would include enforcing css be pre-existing on the page. But like I mentioned, this library doesn't call for much styling at all, so if you remove the few places styling is required (to get minimum use out of the lib), it will save us trouble.

See also Material-UI's discussion on how they handle styling: http://www.material-ui.com/#/customization/styles

**Comment by vkbansal** [comment]
Cool, I'll take a look.

**Comment by vkbansal** [comment]
I cannot simply "not render" the context-menu. The reason why context-menu is always rendered is that I need its dimensions to calculate its position before hand.

What I can do is add opacity toggle. That should work for everyone.
