### ISSUE TITLE
Passing props from trigger to component rendering ContextMenu

### ISSUE THREAD

**Issue by charlie-rudenstal** [vkbansal/react-contextmenu#65]
Props for the rewrite, the API looks way cleaner are more thought-through. Thanks for all your work.

In the previous version, using `connectMenuLayer` and `connect`, it was possible to pass on props from the element triggering the context menu, to the component rendering it. I used this to customize the menu depending on which trigger was clicked.

Example from 1.x.x:

SomeComponent.js:
```
<MenuButton uri={someProp} holdToDisplay={0}>
```

MenuButton.js:
```
const MenuButton = () => (<div>...</div>);
export default contextMenuLayer(MENU_ID, (props) => props)(MenuButton)
```

Menu.js:
```
const Menu = ({item}) => {
  return {
      <ContextMenu identifier={MENU_ID}>
          <MenuItem>Add</MenuItem>
          {item.uri === 'foobar' && <MenuItem>Remove</MenuItem>}
      </ContextMenu>
  }
};
export default menuConnect(Menu);
```

I read the new source code of react-contextmenu and I see no obvious way to do the same thing, now when the higher order function is gone. My question is, are there plans to support a similar use-case in the future, or is this forever dropped as "out of scope" for react-contextmenu? Or am I missing an obvious way to accomplish this with the existing feature set (without tracking the currently opened context menu myself in redux)?

__Update__: Using onShow on ContextMenu makes it possible to access props passed from ContextMenuTrigger if collect is specified to return the props:
```
<ContextMenuTrigger id={MENU_ID} uri={this.props.uri} />
<ContextMenu id={MENU_ID} collect={props => props} onShow={e => doSomething(e.detail.data.uri)} />
```

**Comment by vkbansal** [comment]
Sorry, but I was not able to understand whether you solved the issue yourself or still have a problem?

**Comment by charlie-rudenstal** [comment]
@vkbansal The workaround works by using `collect` and `onShow` to get hold of the props passed by the trigger0. It's still not as convenient as the previous `connect` method, since I will have to use `setState` or similar as a response to onShow. 

I am considering to create my own higher-order-function that would subscribe to `GlobalEventListener` and provide the props to `Menu.js` (from the example above). But since GlobalEventListener is not part of the official API of react-contextmenu I am worried that solution might break.

**Comment by charlie-rudenstal** [comment]
I ended up creating a higher-order-function that looks like this:
https://gist.github.com/charlie-rudenstal/3d5062f911da467b525d6040200334bd

Please let me know if you'd accept a PR with something similar. It would be great to have official support for it.

**Comment by vkbansal** [comment]
Thats really great. Let me try something else that I have in my mind.

If I'm unsuccessful, I let you know. 

PRs are always welcome!

**Comment by barbalex** [comment]
@charlie-rudenstal 
I tried your first solution but `e.detail.data` in the onShow function is always false for me.
The props I passed to ContextMenuTrigger do not turn up.
What could I be missing?

**Comment by barbalex** [comment]
@charlie-rudenstal 
oh, I just noticed that `collect={props => props}` needs to be added to `ContextMenu` _and_ `ContextMenuTrigger` for it to work.
Thanks for your solution!

**Comment by CarstenWickner** [comment]
@vkbansal are you still considering "something else that [you] have in mind", or would now be the time to create a PR with an approach similar to @charlie-rudenstal's?

**Comment by vkbansal** [comment]
@CarstenWickner Thanks for the reminder. I was caught up in other things.

I'll accept a PR if @charlie-rudenstal is still interested in creating one or you can.

**Comment by charlie-rudenstal** [comment]
Thanks all for creating and merging a PR with a solution for this! I have
been away for a while and not had time to open a PR myself.

**Comment by julienw** [comment]
Hey, I realize that without a "collect" function, nothing would happen. What do you think of passing all props by default, if "collect" isn't present ?

Looking at https://github.com/vkbansal/react-contextmenu/blob/a296846497253a72fc3903c2e9c8bfa88955ac78/src/connectMenu.js#L38-L43 that's what I think this code expects.
