### ISSUE TITLE
How to generate dynamic submenus

### ISSUE THREAD

**Issue by rakshans1** [vkbansal/react-contextmenu#66]

**Comment by vkbansal** [comment]
Can you be more descriptive and proved a use case and/or an example?

Else I'll have to close this issue

**Comment by rakshans1** [comment]
I want to create Folder move submenus which will fetch submenu from server while user hover on menu

`<SubMenu title='Another SubMenu'>
  //Load from api here and create another submenu on hover
</SubMenu>`

**Comment by whathejoe** [comment]
Use short-circuit evaluation.

```javascript
{ flag && <Submenu /> }
```
where `flag` is an indicator that you have what you need from the server
