### ISSUE TITLE
Customize submenu widths, margins

### ISSUE THREAD

**Issue by jaredsohn** [vkbansal/react-contextmenu#68]
Is there a way to change the width for each submenu? Also, can I set margins separately per submenu? (I know I can manually add to the margin for individual items but I haven't figured out a way to set a margin to submenu titles.

I've looked through the CSS and the source and haven't found a way thus far (without forking the code.)

**Comment by vkbansal** [comment]
Can you provide some examples like code and/or screenshots?

**Comment by jaredsohn** [comment]
I have included a screenshot below.

I would like the 'Change category' submenu text to line up with the 'Open site' text that appears after the image and I also want the colors in the submenu to be at the left edge of the window (ideally with `margin-left` of 0px, although it set to 5px right now so that 'change category' isn't at the very edge.)

If I set `margin-left` to 15px or so, then I can show the image and have `Open site` line up with `Change category` but that means that in the submenu the colors will be further away from the left-most edge. (If there was an ability to include an image next to a submenu that would fix the margin problem; I don't think that is possible because I just see a `title` prop.

Another thing you can see in the screenshot is that I need a wider menu for the submenu since it includes longer strings and I would prefer that the main menu stays narrow.

<img width="372" alt="screen shot 2017-01-11 at 6 57 14 pm" src="https://cloud.githubusercontent.com/assets/408285/21875386/481cb39c-d830-11e6-97c2-1f012e32c04f.png">

**Comment by vkbansal** [comment]
Which version are you using?

**Comment by jaredsohn** [comment]
I am running 2.0.0-beta.2.

**Comment by vkbansal** [comment]
By default, I include very minimalistic styling, so that you can style the components any way you like. You should be easily able to do what you want.

If you need help with CSS, please provide example code so that I can re-create the menu and may help you.

**Comment by jaredsohn** [comment]
I have been able to style things as I want for each submenu individually but I haven't found a way to style it such that it shows each of the submenus in the way that I want all at once.

I think that I need something like a theoretical "content selector" (http://stackoverflow.com/questions/1520429/is-there-a-css-selector-for-elements-containing-certain-text) so that I can indicate which submenu I want to style a certain way. Alternatively the component could be updated to allow setting ids/classes in certain places that makes it easier to create selectors. When I look at the DOM it otherwise seems hard to create a rule that applies to one submenu and not to others since the elements themselves have the same HTML.

One thing that I may try is to apply CSS to nodes individually as they are found via JavaScript (as an answer in the above link suggests.)

**Comment by vkbansal** [comment]
You can use `props.attributes` on `MenuItem' to pass any `className` you want.
Also, you can use [classnames](https://www.npmjs.com/package/classnames) to add classes based on the text you need.

**Comment by jaredsohn** [comment]
I want to pass a className to a SubMenu instead of to a MenuItem.

**Comment by vkbansal** [comment]
Cool, I'll add the ability

**Comment by jaredsohn** [comment]
Great; thanks!

**Comment by vkbansal** [comment]
I've made the changes:
https://github.com/vkbansal/react-contextmenu/commit/98019d5ec90fd1e554b99e8a1e9b214f916389a4

Let me know if this works for you.

**Comment by jaredsohn** [comment]
Thanks; I am taking a look.

**Comment by jaredsohn** [comment]
FWIW, the changes from f16ce5b7e21c3f1d7995fc09f2f336fbf44a1502 messed up my styles a bunch (I see a text cursor instead of a pointer and my row heights are wrong.) I'm able control widths separately for submenus so far and over the next day I'll check if it works for margins as I fix up my styles.

**Comment by jaredsohn** [comment]
All done. This works for me; thanks!
