### ISSUE TITLE
left click trigger

### ISSUE THREAD

**Issue by ekatebi** [vkbansal/react-contextmenu#70]
Is there a way to bring up the context menu by left mouse click?

-ed

## Version
2.0.0

## Test Case
http://jsbin.com/sacerobuxi/edit?html,js,output

**Comment by vkbansal** [comment]
duplicate of #50

**Comment by jeffkillian** [comment]
If you want to bring it up with left click, one work around is to set the `holdToDisplay` prop to `. As long as they don't click within 1ms (unlikely), it triggers when left clicking as well.
