### ISSUE TITLE
"shouldTrigger" prop?

### ISSUE THREAD

**Issue by stevenmusumeche** [vkbansal/react-contextmenu#71]
Hello, and thank you for this wonderful package.  I am building an application where I only want to enable the context menu when certain conditions are met (for example, some value in state is true).  

Is there a way to pass a prop to `ContextMenuTrigger` to make it ignore right clicks and display the default browser context menu when a prop like `shouldTrigger` is false?  

I am able to conditionally wrap my component with `ContextMenuTrigger`, however, it is causing a problem for my use case. When the condition becomes true, the nodes inside of `ContextMenuTrigger` are recreated by React, and thus the user's selected text is removed.

**Comment by stevenmusumeche** [comment]
wow @vkbansal, that was fast  Thank you so much! Do you have an idea of when this will be included in a release on npm?

**Comment by vkbansal** [comment]
Most probably by the weekend.

**Comment by vkbansal** [comment]
I've released v2.2.0 with this change. Happy Coding!

**Comment by stevenmusumeche** [comment]
thank you!
