### ISSUE TITLE
onHide is being triggered when contextmenu is opened

### ISSUE THREAD

**Issue by garetmckinley** [vkbansal/react-contextmenu#78]
## Description

The `onHide` event is triggered when the contextmenu opens and closes.

## Reproduction

http://www.webpackbin.com/4k70v-eYf

**Comment by vkbansal** [comment]
Thanks for reporting. I'll take a look.

**Comment by vkbansal** [comment]
I've fixed it in 	2ffca3c

**Comment by garetmckinley** [comment]
Awesome! How soon are you expecting to have a release with this fix in it?

**Comment by vkbansal** [comment]
I'll make a patch release within couple of days

**Comment by vkbansal** [comment]
released v2.3.0

**Comment by garetmckinley** [comment]
Awesome 🙌
