### ISSUE TITLE
Context menu contents depending on target

### ISSUE THREAD

**Issue by bramdevries** [vkbansal/react-contextmenu#8]
I'm working on an application that makes extensive use of context-menu's. 

We built a wrapper around `ContextMenu` so it fits our use-case. In some cases we want to display a different component or add an icon, ... All this works fine.

There is one component however that renders a tree, which contains a lot `<Node />` components. Each of these nodes can have different types, and depending on the type we add or remove options from the context menu. Our current solution is to render a `<NodeMenu />` for each `<Node />`, all of these menu's would render a `ContextMenu` with an id such as `node-menu-${this.props.id}`. This method did causes performance issues when about 10-20 `<Node />`'s are rendered.

So we're opting to have a single `NodeMenu` on the page and make each `<Node />` a `ContextMenuLayer`, but we ran into some issues. 

By using this approach we cannot add/remove options based on the properties given in `configure()`, because these props are only available during the click handlers. I've tried using the `monitor` included to get access to the item by using `monitor.getItem()`, but no luck.

So my question is:

Do you have any example code on how to properly use `monitor.getItem()` for a use-case like this?

**Comment by vkbansal** [comment]
So what you are asking is "How to render different items based on which `<Node/>` was (right) clicked" ??
Correct me if I'm wrong.

**Comment by vkbansal** [comment]
I've added a `connect` helper in `v1.2`. You can have look at [multiple-targets example](https://github.com/vkbansal/react-contextmenu/blob/ce3e374770747914c984aa937861a6c5975adf9c/examples/multiple-targets/menu.js) and [demo](http://vkbansal.github.io/react-contextmenu/#/multiple-targets).

Let me know if this what you were looking for.

**Comment by bramdevries** [comment]
Works nice, thanks for the quick response
