### ISSUE TITLE
Feature request: Make component more agnostic

### ISSUE THREAD

**Issue by iliastsangaris** [vkbansal/react-contextmenu#87]
I like this project and am considering forking it to implement a feature request, but wanted to document the request first.

It would be great to have `ContextMenu` be more of generic `Menu` component with the option for it to become a context menu via a prop passed to the trigger component.

Something along the lines of `<MenuTrigger context={true} />`.

Thanks for the project!

**Comment by vkbansal** [comment]
I've got similar requests in past.

Let me explain my point of view:

The definition of a context-menu (AFAIK) is a menu that opens on right-click.
If we make this a generic menu, then:
1. It will break existing user code.
2. Project might have to be renamed. (I'm not comfortable with this option).

I do not understand the use case for opening a menu on left click. For such cases, I prefer using something like dropdown menu.

Please correct me if I'm wrong and let me know the use case of what you are proposing.

**Comment by danbovey** [comment]
I was thinking about writing this feature too but instead found that calling the method `handleContextClick` from the `ContextMenuTrigger` was enough flexibility to give the context menu other roles within my application.

For example, a button like this (http://i.imgur.com/5Qsu2yW.png) opens the context menu manually. It works in the same way a drag handle works for a draggable div - the button is the only area the user can left click to open the menu.

```js
let contextTrigger = null;

const toggleMenu = e => {
    if(contextTrigger) {
        contextTrigger.handleContextClick(e);
    }
};

return (
    // Handles my right clicking of the artwork
    <ContextMenuTrigger ref={c => contextTrigger = c}>
        <img src="artwork.jpg" />
        // The artwork has a menu icon on top of it, allowing for left click
        <button onClick={toggleMenu}><Icon name="more_vert" /></button>
    </ContextMenuTrigger>
    <ContextMenu>
        ...
    </ContextMenu>
);
```

It doesn't turn it into a perfect dropdown menu but that's not what this component is, and if you need that then you should install a dedicated dropdown-menu component.

**Comment by vkbansal** [comment]
@danbovey Can you create new FAQs section in Readme and document the same and open a PR?

**Comment by danbovey** [comment]
^ Done. I'd suggest moving the FAQs to the Wiki, the README already feels extremely long for such a simple API.

Maybe, convert the props documentation into table format?

| Property    | Type    | Required? | Description                            |
|-------------|---------|-----------|----------------------------------------|
| id          | String  | ✓         | A unique identifier for a menu.        |
| hideOnLeave | Boolean |           | Hides the context menu on mouse leave. |

**Comment by danbovey** [comment]
Table format PR'ed in #90 😄
