### ISSUE TITLE
Keyboard Shorcut Accessibility

### ISSUE THREAD

**Issue by gregtatum** [vkbansal/react-contextmenu#88]
Would you accept a contribution for keyboard shortcuts? Arrow keys for navigation, and enter for selecting the item.

**Comment by vkbansal** [comment]
PRs are always welcome!!

**Comment by gregtatum** [comment]
Thanks! We're evaluating react-contextmenu for a project, and keyboard access is probably important. I'll re-open an issue if I start working on a PR.
