### ISSUE TITLE
Breaks table markup

### ISSUE THREAD

**Issue by dsemenovsky** [vkbansal/react-contextmenu#9]

**Comment by vkbansal** [comment]
@dsemenovsky Can you please describe the problem in detail?

**Comment by pgruenbacher** [comment]
I think I'm having this issue too.
Basically if a the contextMenuLayer is wrapping a table row or column, then it'd rendering a div element within the table which obviously breaks it.

**Comment by pgruenbacher** [comment]
https://github.com/vkbansal/react-contextmenu/blob/master/src/contextmenu-layer.js#L59-L64

**Comment by pgruenbacher** [comment]
one work-around I sometimes do is to let the user specify the element type in the props and then render it dynamically using React.createElement

**Comment by vkbansal** [comment]
Fixed in v1.3.0

**Comment by sourabhlk** [comment]
yeah same issue I am wrapping <ContextMenuTrigger to table which it breaks and contextmenu works weird, suggest some solution

**Comment by vkbansal** [comment]
There is an option renderTag

**Comment by vkbansal** [comment]
https://github.com/vkbansal/react-contextmenu/blob/master/docs/api.md
