### ISSUE TITLE
Force shutdown of the menu

### ISSUE THREAD

**Issue by kemperrr** [vkbansal/react-contextmenu#91]
I would like to see the forced closing of the context menu

Example: 
`import { hideMenu } from "react-contextmenu"`

**Comment by vkbansal** [comment]
I can't understand your request. Can you explain it more clearly?

**Comment by kemperrr** [comment]
I want to close the menu not by clicking the mouse button, but through the function

**Comment by vkbansal** [comment]
This is not officially supported but you can

```js
import { hideMenu } from 'react-contextmenu/modules/actions'

hideMenu();
```

**Comment by kemperrr** [comment]
In this case, there are errors
![image](https://cloud.githubusercontent.com/assets/10745678/24322046/b704fb56-118e-11e7-871f-bc64b06b3d18.png)

**Comment by vkbansal** [comment]
Can you share the code that is causing this?

**Comment by kemperrr** [comment]
ye
![image](https://cloud.githubusercontent.com/assets/10745678/24322074/42ac7e5e-118f-11e7-9c1b-b019f7e7fed3.png)

**Comment by vkbansal** [comment]
Where have you mounted the `ContextMenu` or `ContextTrigger`?

**Comment by kemperrr** [comment]
in "OrtherOne"

**Comment by vkbansal** [comment]
Can you share a working piece of code? Something like a jsbin or gh-repo?

**Comment by kemperrr** [comment]
Alas, I can not do this

**Comment by Seldaek** [comment]
@kemperrr your problem is that you are hiding the menu  while react renders, so it's not done rendering the open menu but you are already closing it. 

I think it'd be better to do the check in the `componentDidUpdate` lifecycle method. You probably want something like that in there:

```
if (this.props.mainSelected != 3) {
    hideMenu();
} else {
    showMenu();
}
```

**Comment by kemperrr** [comment]
@Seldaek Thank you! It worked!
