### ISSUE TITLE
Add ARIA attributes

### ISSUE THREAD

**Issue by vkbansal** [vkbansal/react-contextmenu#92]
https://www.w3.org/TR/wai-aria-practices-1.1/#intro

- [x] add aria-attributes
- [x] add keyboard navigation

**Comment by danbovey** [comment]
Nit: `aria-orientation: undefined` is not a valid ARIA attribute so it gets flagged on tests like Lighthouse. See my fork for fix to this and #98: https://github.com/danbovey/react-contextmenu/commit/d6a927bb36ba7afce8ea1f0032d175b98ce2bc6c

**Comment by vkbansal** [comment]
@danbovey can you open a PR with ARIA fix?
