### ISSUE TITLE
Tooltip use case

### ISSUE THREAD

**Issue by Seldaek** [vkbansal/react-contextmenu#94]
Hey, I needed a tooltip component and after trying react-tooltip we settled on "abusing" react-contextmenu for tooltips, because it works way better when you need a large set of tooltips. React-tooltip forced us to have an instance of the tooltip in the dom for every tooltip, while with this lib we can only have one instance of the tooltip that is updated/rendered using the needed info on demand. That makes rendering a lot faster..

I am not sure if you would be interested in including the functionality in your lib or not, but here are the two components I use to show the tooltip and trigger them..

```js
import React from 'react';
import {hideMenu, showMenu} from "react-contextmenu/modules/actions";
import {ContextMenu} from "react-contextmenu";

function excludeProps(obj, props) {
    var clone = Object.assign({}, obj);
    props.forEach((prop) => {
        delete clone[prop];
    });

    return clone;
}

var Tooltip = React.createClass({
    propTypes: {
        id: React.PropTypes.string.isRequired,
        collect: React.PropTypes.func, // must return {component: ...} which will be placed inside the tooltip
        disabled: React.PropTypes.bool, // optional, defaults to false
        component: React.PropTypes.any,
    },
    getDefaultProps: function () {
        return {
            disabled: false,
            component: 'span',
        };
    },
    handleMouseOver: function (e) {
        if (this.props.disabled) {
            return;
        }

        e.persist();

        clearTimeout(this.mouseOutTimeoutId);
        this.mouseOverTimeoutId = setTimeout(
            () => this.showMenu(e),
            700
        );
    },
    handleMouseOut: function (e) {
        if (this.props.disabled) {
            return;
        }

        e.persist();

        clearTimeout(this.mouseOverTimeoutId);
        this.mouseOutTimeoutId = setTimeout(
            () => this.hideMenu(e),
            50
        );
    },
    hideMenu: function () {
        hideMenu({
            id: this.props.id,
        });
    },
    showMenu: function (e) {
        const x = (e.clientX || (e.touches && e.touches[0].pageX)) + 15;
        const y = (e.clientY || (e.touches && e.touches[0].pageY)) + 15;

        this.hideMenu();
        showMenu({
            position: {x, y},
            target: this.ref,
            id: this.props.id,
            data: this.props.collect(this.props),
        });
    },
    render() {
        const props = Object.assign({}, excludeProps(this.props, ['id', 'collect', 'message', 'disable', 'component', 'children']), {
            onMouseOver: this.handleMouseOver,
            onMouseOut: this.handleMouseOut,
            ref: (ref) => { this.ref = ref; },
        });

        return React.createElement(this.props.component, props, this.props.children);
    }
});

var TooltipRenderer = React.createClass({
    propTypes: {
        id: React.PropTypes.string.isRequired,
        className: React.PropTypes.string,
    },
    onShowMenu: function (args) {
        this.setState({
            component: args.detail.data.component,
        });
    },
    getDefaultProps: function () {
        return {
            className: '',
        };
    },
    getInitialState: function () {
        return {};
    },
    render: function () {
        return <ContextMenu className={'tooltip-renderer ' + this.props.className} id={this.props.id} onShow={this.onShowMenu}>
            {this.state.component}
        </ContextMenu>
    }
});

export default TooltipRenderer;
```

**Comment by vkbansal** [comment]
I could not have even imagined that one could do this. Awesome! I could add this to readme.

`Tooltip` closely resembles `ContextMenuTrigger`.

**Comment by Seldaek** [comment]
Yeah Tooltip is basically the trigger, except it works on hover and not right-click. I just updated it with a couple tweaks I made here..

But yeah I don't know if it's worth having in the library itself, but I guess it makes a good use case example.

**Comment by IamCarbonMan** [comment]
Perhaps it would be possible to have ContextMenuTrigger accept a prop for the event it will show on. Not sure if there's a way to register a component event handler using a string prop of the event or something like that. Otherwise, maybe just a prop that recognizes a few different events like 'contextmenu', 'mouseover', 'click', 'dblclick'.

**Comment by Seldaek** [comment]
Sadly it's not that easy.. I updated the code further to support touch events now and will require some more fixes possibly after more testing.

There are more considerations than just listening to a different event. You wanna have a delay etc. I can update the code here when we're done if there is an interest.

**Comment by IamCarbonMan** [comment]
https://github.com/vkbansal/react-contextmenu/blob/master/docs/faq.md

I didn't see this before, but the method described there may be a better way to support triggering the menu arbitrarily. It does use refs and it is a bit messy, but perhaps you could create a class that encapsulates this and passes the context menu callback down somehow.
