### ISSUE TITLE
Long left click triggers context menu 

### ISSUE THREAD

**Issue by brmscheiner** [vkbansal/react-contextmenu#97]
## Version
2.0.0

## Test Case
https://vkbansal.github.io/react-contextmenu/#/simple-menu

## Steps to reproduce
Left click inside the well for an extended amount of time

## Expected Behavior
Nothing 

## Actual Behavior
Context menu appears

**Comment by vkbansal** [comment]
Read `holdToDisplay` description [here](https://github.com/vkbansal/react-contextmenu#contextmenutrigger-)

**Comment by brmscheiner** [comment]
My fault.. when I went through it the first time I stopped reading after "This is applicable only for touch screens."
