### ISSUE TITLE
Disable Contextmenu on mobile

### ISSUE THREAD

**Issue by tedicela** [vkbansal/react-contextmenu#98]
How to disable contextmenu on mobile and let the setted events to trigger normally (onclick/ondbclick) setted on the ContextMenuTrigger tag?

The html tag that trigger the menu has onclick and ondbclick events. These events aren't fired on mobile devices but on PC they get fired. The context menu is fired on right-click(Desktop) and on long-press(mobile). Is possible to disable completely like there is no contextmenu on mobile?

**Comment by danbovey** [comment]
You don't need to get rid of your context menus on mobile, it's just this line: https://github.com/vkbansal/react-contextmenu/blob/master/src/ContextMenuTrigger.js#L61 that's preventing anything being regularly clicked on mobile.

Opened a pull request to remove it: #102

I don't know why it's there, holding for right click and opening the menu doesn't cause a link to be clicked, and so without it `onclick` events work for content inside the `ContextMenuTrigger`!
