### ISSUE TITLE
SubMenu display when containing lots of subItems

### ISSUE THREAD

**Issue by nkahnfr** [vkbansal/react-contextmenu#99]
## Version
2.4.0

## Test Case
http://jsbin.com/nequdoloru/edit?js,output

## Steps to reproduce
Create a menu with a sub-menu having lots of sub-items (100 in the test case above).

## Expected Behavior
Be able to see and select any sub-item.
Two cases should be taken into account:
1. All sub-items can be displayed on the page by optimizing SubMenu position (i.e. centering it on the page instead of setting its ```bottom``` position to zero relative to its parent menu)
2. All sub-items cannot be displayed on the page even after optimizing SubMenu position. Being able to scroll the sub-menu seems the "easiest" solution in that case.

## Actual Behavior
Only able to see part of the sub-items with no way to access others that are just hidden since they overflow the page.

**Comment by yotamberk** [comment]
Why don;t you use `overflowY: scroll`? it doesn't make sense to have that many submenu items in a contextmenu...

**Comment by nkahnfr** [comment]
By default the context menu is hidden on page scroll. I tried using ```overflowY: scroll``` but you always somehow scroll the page when scrolling the submenu so it's not option as is.

Regarding the number of submenu items I think it depends on your usage. I am using context menu to ease moving nodes in a tree (something like a mind map) instead of drag and drop that gets difficult to use when you have many nodes in your tree. Since I am presenting the whole tree in the context menu, it's common for me to get a lot of submenus and a lot of items in each of them.

That being said I worked on a fix/evolution (https://github.com/nkahnfr/react-contextmenu/commit/5fc915bb1686bc022f80a9782a56e90c899036e5) and I can create a PR if it makes sense.

**Comment by terraswat** [comment]
@yotamberk I have this same issue and it only involves 30 items on a submenu. This is not very common in our app, however  it does occur and there is no way for the user to select some items on the list.

I played with overflowY: scroll on the submenu with no luck. A scrollbar area displays, but there is no handle to scroll with. It seems this functionality would be valuable in the master branch.

Would you suggest a way to use overflowY as you suggested?

**Comment by yotamberk** [comment]
With `overflowY: scroll` you must define the `height` property. 
try defining `height: 200px` with `overflowY: true`.
That should do the trick

**Comment by terraswat** [comment]
Yes, that did to the trick! Except the style needed to go in css because it needed to be applied to the .react-contextmenu between the submenu's .react-contextmenu-item and its list of .react-contextmenu-item children.
